### ISSUE TITLE
feat: assertions should report the actual value

### ISSUE THREAD

**Issue by naimdjon** [TestFX/TestFX#125]
Given the following assertion:

```
verifyThat("#errorMessage", hasText("The error message!")); 
```

if the expected and actual values differ, TestFX just reports that the node did not have that text. The preferred behaviour would be to tell what the actual value was, just like traditional junit `assertEquals()`.

**Comment by psyren89** [comment]
I get this:
```java.lang.AssertionError: 
Expected: Node should have label 102.78
     but: was "#sensorAzimuthValue" Screenshot saved as /(...)/screenshot1423533621393.png
 (...)
Caused by: java.lang.AssertionError: 
Expected: Node should have label 102.78
     but: was "#sensorAzimuthValue"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.loadui.testfx.Assertions.verifyThat(Assertions.java:32)
	... 29 more```

Any news on this?
