### ISSUE TITLE
Is there a way to solve ThreadDeath for Travis CI?

### ISSUE THREAD

**Issue by Daytron** [TestFX/TestFX#161]
I got the following build errors:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.daytron.flipit.map.creator.MainAppTest
Xlib:  extension "RANDR" missing on display ":99.0".
[TestFX] User mouse movement detected. Aborting test.
Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 3.048 sec <<< FAILURE! - in com.github.daytron.flipit.map.creator.MainAppTest
clickGenerateButtonAtStartTest(com.github.daytron.flipit.map.creator.MainAppTest)  Time elapsed: 2.838 sec  <<< ERROR!
java.lang.ThreadDeath: null
    at java.lang.Thread.stop(Thread.java:850)
    at org.loadui.testfx.utils.UserInputDetector.userInputDetected(UserInputDetector.java:58)
    at org.loadui.testfx.utils.UserInputDetector.assertPointsAreEqual(UserInputDetector.java:42)
    at org.loadui.testfx.FXScreenController.move(FXScreenController.java:86)
    at org.loadui.testfx.GuiTest.move(GuiTest.java:846)
    at org.loadui.testfx.GuiTest.move(GuiTest.java:859)
    at org.loadui.testfx.GuiTest.click(GuiTest.java:628)
    at com.github.daytron.flipit.map.creator.MainAppTest.clickGenerateButtonAtStartTest(MainAppTest.java:64)
Results :
Tests in error: 
  MainAppTest.clickGenerateButtonAtStartTest:64->GuiTest.click:628->GuiTest.move:859->GuiTest.move:846 » ThreadDeath
```

I also use this script for my .yml file:

```
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
```

A way to disable mouse input  detection on test is a solution I can think of.

**Comment by brcolow** [comment]
Closing due to inactivity and because this an issue about the legacy, unmaintained version of TestFX.
