### ISSUE TITLE
The error type () method with special characters

### ISSUE THREAD

**Issue by RobsonSantiago3** [TestFX/TestFX#179]
when I try to insert a special character (_ + - @ & *% $ ¨) generates an error and the test for the implementation.

type("kj5m9c33").type('@');

java.lang.IllegalArgumentException: No KeyCode found for character: @
	at org.loadui.testfx.utils.KeyCodeUtils.findKeyCode(KeyCodeUtils.java:33)
	at org.loadui.testfx.GuiTest.type(GuiTest.java:1004)
	at br.com.grupopalma.testFx.TestFx.testePrincipal(TestFx.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by hastebrot** [comment]
Hi!

This has been an bug in [v3.1.2](https://github.com/TestFX/TestFX/releases/tag/v3.1.2) and has been fixed in [v4.0.0-SNAPSHOT](https://github.com/TestFX/TestFX/releases/tag/v4.0.0-SNAPSHOT). For 3.1.2 you might use a work-around as described in #74.

**Comment by RobsonSantiago3** [comment]
this same corrects for other keyboards?

**Comment by hastebrot** [comment]
No, it is not agnostic to the keyboard layout in 3.1.2. You need to press the buttons you would normally press on the keyboard.

**Comment by RobsonSantiago3** [comment]
if my keyboard I'm doing in Portuguese do so @ <code>press(KeyCode.SHIFT).press(KeyCode.DIGIT2).release(KeyCode.DIGIT2).release(KeyCode.SHIFT) </code>(<code> SHIFT+ digit2 </code>) however he does not have any character typed
