### ISSUE TITLE
Test FX doesn't appear to correctly tear down.  Causes hanging.

### ISSUE THREAD

**Issue by purringpigeon** [TestFX/TestFX#185]
Below is a sample test case.  It works fine with either of the tests running individually, but never both.

public class SampleWorkspaceTest extends GuiTest{

public Parent getRootNode() {

FXMLLoader loader = new FXMLLoader();
 Parent node = null;
 try {
 node = loader.load(
 this.getClass().getResource(“/org/sample/workspace/SampleWorkSpace.fxml”).openStream());
 } catch (IOException e) {
 // TODO Auto-generated catch block
 e.printStackTrace();
 }

return node;
 }

@before
public void login() {
//login to server;
}
 @Test
 public void searchByPolicyNumber() throws Exception{
 TableView tv = (TableView)find(“#resultsTable”);

click(“#policyNumberTextField”).type(“123456″);
 click(“#searchButton”);
waitUntil(tv, TableViews.containsCell(“123456″));
 Assertions.verifyThat(tv, TableViews.containsCell(“123456″));

}
 @Test
 public void searchByPolicyName() throws Exception{
 TableView tv = (TableView)find(“#resultsTable”);

click(“#policyNameTextField”).type(“Some Policy Name”);
click(“#searchButton”);
waitUntil(tv, TableViews.containsCell(“Some Policy Name”), 30);
 Assertions.verifyThat(tv, TableViews.containsCell(“Some Policy Name”));

}
 }

The system logs in successfully, and runs the test without issue. However the second test (in this case searchByPolicyName) – times out on the waitUntil()… All UI interaction is with the correct view/stage, but the wait times out with the following error:

java.lang.RuntimeException: java.util.concurrent.TimeoutException
 at org.loadui.testfx.utils.TestUtils.awaitCondition(TestUtils.java:49)
 at org.loadui.testfx.GuiTest.waitUntil(GuiTest.java:364)
 at org.idahosif.test.SampleWorkspaceTest.searchByPolicyName(SampleWorkspaceTest.java:63)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
 at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
 at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
 Caused by: java.util.concurrent.TimeoutException
 at org.loadui.testfx.utils.TestUtils.awaitCondition(TestUtils.java:43)
… 26 more

When I perform a findAll(“#resultsTable”) – I get one on the first test, and two on the second test, which I assume is the reason for the timeout – it’s looking at the first table in the hierarchy, rather than the later.

Additional error that I get – which I can’t figure out is after it loads the FXML and before any tests are executed, the following error is logged to the console, but it doesn’t appear to cause any issues…

java.util.concurrent.TimeoutException: Timeout waiting for task.
 at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
 at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
 at org.loadui.testfx.utils.FXTestUtils.invokeAndWait(FXTestUtils.java:131)
 at org.loadui.testfx.utils.FXTestUtils.invokeAndWait(FXTestUtils.java:156)
 at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:123)
 at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:101)
 at org.loadui.testfx.GuiTest.setupStage(GuiTest.java:91)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
 at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
 at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
 at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
 at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
 at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
 at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
 at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
 at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
 at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

I am not sure if this gives you the data you need – however I am at a loss on why the TestFX framework isn’t tearing down correctly – and how I can manage it.

If I attempt to add closeCurrentWindow() in the searchByPolicyNumber() method, at the end, it fires before the verifyThat executes, which I am guessing is threading related and the window closes, the second test doesn’t execute and the first hangs.

**Comment by purringpigeon** [comment]
Hello I was hoping to see if there was anything I could do to correct the issue I am having with TestFX.  Will 4.0 solve this issue?  Is there another way to call these so that we don't see this issue?

Thanks.

**Comment by hastebrot** [comment]
Hi! Sorry for the late reply.

Could you try to put `Platform.setImplicitExit(false);` before the statement that closes the window`?

--Benjamin

**Comment by purringpigeon** [comment]
I tried that and it closed the window correctly after the first test so that the second test only had one result:

I did this in the test to check:
Set<Node> node = findAll("#resultsTable");
node.stream().forEach(n -> System.out.println("test1: " + n.toString()));

test1: TableView[id=resultsTable, styleClass=table-view]
test2: TableView[id=resultsTable, styleClass=table-view]

However, test 2 still did not complete.  I got the same timeout error:
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at org.loadui.testfx.utils.TestUtils.awaitCondition(TestUtils.java:49)
	at org.loadui.testfx.GuiTest.waitUntil(GuiTest.java:364)
	at org.idahosif.test.SampleWorkspaceTest.searchByFEIN(SampleWorkspaceTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.util.concurrent.TimeoutException
	at org.loadui.testfx.utils.TestUtils.awaitCondition(TestUtils.java:43)
	... 26 more

What is also weird - is that I continue to get the following exception each time getRootNode is called.  Perhaps this is the real issue?

java.util.concurrent.TimeoutException: Timeout waiting for task.
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.loadui.testfx.utils.FXTestUtils.invokeAndWait(FXTestUtils.java:131)
	at org.loadui.testfx.utils.FXTestUtils.invokeAndWait(FXTestUtils.java:156)
	at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:123)
	at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:101)
	at org.loadui.testfx.GuiTest.setupStage(GuiTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by purringpigeon** [comment]
I think that the issue may in the way the framework is looking up something.  I changed test 2 to sleep rather that waitUntil...

	@Test
	public void searchByFEIN() throws Exception{
		TableView<PolicyContextDTO> tv = (TableView<PolicyContextDTO>)find("#resultsTable");
		 Set<Node> node = findAll("#resultsTable");
		 node.stream().forEach(n -> System.out.println("test2: " + n.toString()));
		
		click("#taxIdTextField").type("123456799");
		click("#searchButton");
		System.out.println("About to wait....." + new Date());
		//waitUntil(tv, TableViews.containsCell("123456799"), 30);
		sleep(10000);
		System.out.println("Finished waiting....." + new Date());
		Assertions.verifyThat(tv, TableViews.containsCell("123456799"));
	}

The error on the verifyThat() is the following: 

java.lang.AssertionError: 
Expected: The table does not contain a cell with value '123456799'
     but: was <TableView[id=resultsTable, styleClass=table-view]> Screenshot saved as C:\workspace\powersuite-javafx-ui\testfx\screenshot1423582041589.png
	at org.loadui.testfx.Assertions.verifyThat(Assertions.java:36)
	at org.loadui.testfx.Assertions.verifyThat(Assertions.java:25)
	at org.idahosif.test.SampleWorkspaceTest.searchByFEIN(SampleWorkspaceTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.AssertionError: 
Expected: The table does not contain a cell with value '123456799'
     but: was <TableView[id=resultsTable, styleClass=table-view]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.loadui.testfx.Assertions.verifyThat(Assertions.java:32)
	... 27 more

However if you look at the attached screenshot - you will see that the table clearly has a value.  ![textfxsceenshot](https://cloud.githubusercontent.com/assets/7788527/6129963/39c050ba-b0ff-11e4-999a-2b5ac4fbc0bf.png)


However if I run this test alone - with only the @Before and @After running - then it works just fine.

I am wondering if something in the comparison of nodes/cells is holding a reference to the previous test?

**Comment by purringpigeon** [comment]
I changed this test to use some fake data, rather than the real call to the server, which allowed both tests to complete.  I added another to test for an error condition:

	@Test
	public void causeError() throws Exception{
		TableView<PolicyContextDTO> tv = (TableView<PolicyContextDTO>)find("#resultsTable");
		click("#searchButton");
		Assertions.verifyThat(find(".error"), d->d.isVisible());
		closeCurrentWindow();
		Assertions.verifyThat("#policyNameTextField", t-> {
			CustomTextField ct = (CustomTextField)t;
			return ct.getRight().isVisible();
		});
		
	}

What is weird is that if this test runs first, then the second test will fail with the same type of assertion error as above: Table does not contain a cell with value....
![failed test](https://cloud.githubusercontent.com/assets/7788527/6148349/fafb82ea-b1bd-11e4-82d4-bcad3507953e.png)

However if the new test runs last - then it all works:
![allsuccessful](https://cloud.githubusercontent.com/assets/7788527/6148361/09949ddc-b1be-11e4-9028-1973d421ca2f.png)

There is no difference to the content of the tests, other than the test name which changes the order of execution.

I thought this might help in tracking down the issue.

**Comment by hastebrot** [comment]
Thanks for the examples and screenshots. I'll give this a shot on the weekend.

**Comment by purringpigeon** [comment]
Hello, just wanted to touch base and see if you had determined anything with my issue?  Thanks.

**Comment by hastebrot** [comment]
As 
Hi! As I understand correctly, I you run `shouldCauseError()` and then `searchByPolicyNumber()` the last test will cause the error `Table does not contain a cell with value...`. If it runs in the opposite order it succeeds. Am I correct?

~~~java
@Test
public void searchByPolicyNumber() throws Exception {
    TableView tv = (TableView)find(“#resultsTable”);

    click(“#policyNumberTextField”).type(“123456″);
    click(“#searchButton”);
    waitUntil(tv, TableViews.containsCell(“123456″));
    Assertions.verifyThat(tv, TableViews.containsCell(“123456″));
}
~~~

~~~java
@Test
public void shouldCauseError() throws Exception{
    TableView<PolicyContextDTO> tv = (TableView<PolicyContextDTO>)find("#resultsTable");
    click("#searchButton");
    Assertions.verifyThat(find(".error"), d->d.isVisible());
    closeCurrentWindow();
    Assertions.verifyThat("#policyNameTextField", t-> {
        CustomTextField ct = (CustomTextField)t;
        return ct.getRight().isVisible();
    });
}
~~~

**Comment by purringpigeon** [comment]
Yes that is correct.

Additionally if the searchByPolicy and the searchByFEIN are run (without the third shouldCauseError test) and they connect to the real HTTP service which runs in the background (rather than a mock service which runs on the FX thread), the second test will always fail in a similar manner.

So I am not sure if this is a threading issue, a scoping issue, or something in between.

Thanks.

**Comment by brcolow** [comment]
Closing due to inactivity and because this is an issue about the legacy, unmaintained version of TestFX.
