### ISSUE TITLE
ConcurrentModificationException in find

### ISSUE THREAD

**Issue by naimdjon** [TestFX/TestFX#189]
I am using version `3.1.2` because we can't migrate to JavaFX 8, just yet. Using  `find()` results in ConcurrentModificationException. It happens only 1/10 times and not easily reproducible.  I have tried adding `awaitEvents()` around, but it still happens from time to time. Any suggestions on how to come around this? 

``` java
Error Message

java.util.ConcurrentModificationException
Stacktrace

java.util.ConcurrentModificationException
    at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:386)
    at java.util.AbstractList$Itr.next(AbstractList.java:355)
    at com.sun.javafx.scene.shape.PathUtils.configShape(PathUtils.java:45)
    at javafx.scene.shape.Path.impl_configShape(Path.java:251)
    at javafx.scene.shape.Path.impl_configShape(Path.java:89)
    at javafx.scene.shape.Shape.impl_computeGeomBounds(Shape.java:864)
    at javafx.scene.Node.updateGeomBounds(Node.java:3552)
    at javafx.scene.Node.getGeomBounds(Node.java:3505)
    at javafx.scene.Node.getLocalBounds(Node.java:3453)
    at javafx.scene.Node.updateTxBounds(Node.java:3616)
    at javafx.scene.Node.getTransformedBounds(Node.java:3399)
    at javafx.scene.Parent.recomputeBounds(Parent.java:1510)
    at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1374)
    at javafx.scene.Node.updateGeomBounds(Node.java:3552)
    at javafx.scene.Node.getGeomBounds(Node.java:3505)
    at javafx.scene.Node.getLocalBounds(Node.java:3453)
    at javafx.scene.Node.updateTxBounds(Node.java:3616)
    at javafx.scene.Node.getTransformedBounds(Node.java:3399)
    at javafx.scene.Parent.updateCachedBounds(Parent.java:1584)
    at javafx.scene.Parent.recomputeBounds(Parent.java:1523)
    at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1374)
    at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3022)
    at javafx.scene.Node.updateGeomBounds(Node.java:3552)
    at javafx.scene.Node.getGeomBounds(Node.java:3505)
    at javafx.scene.Node.computeLocalBounds(Node.java:3568)
    at javafx.scene.Node.updateLocalBounds(Node.java:3598)
    at javafx.scene.Node.getLocalBounds(Node.java:3459)
    at javafx.scene.Node.updateTxBounds(Node.java:3616)
    at javafx.scene.Node.getTransformedBounds(Node.java:3399)
    at javafx.scene.Parent.recomputeBounds(Parent.java:1510)
    at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1374)
    at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3022)
    at javafx.scene.Node.updateGeomBounds(Node.java:3552)
    at javafx.scene.Node.getGeomBounds(Node.java:3505)
    at javafx.scene.Node.getLocalBounds(Node.java:3453)
    at javafx.scene.Node.updateTxBounds(Node.java:3616)
    at javafx.scene.Node.getTransformedBounds(Node.java:3399)
    at javafx.scene.Parent.updateCachedBounds(Parent.java:1584)
    at javafx.scene.Parent.recomputeBounds(Parent.java:1523)
    at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1374)
    at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3022)
    at javafx.scene.Node.updateGeomBounds(Node.java:3552)
    at javafx.scene.Node.getGeomBounds(Node.java:3505)
    at javafx.scene.Node.getLocalBounds(Node.java:3453)
    at javafx.scene.Node$MiscProperties$2.computeBounds(Node.java:6280)
    at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9108)
    at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9078)
    at javafx.scene.Node.getBoundsInLocal(Node.java:3131)
    at org.loadui.testfx.utils.FXTestUtils.isNodeWithinSceneBounds(FXTestUtils.java:259)
    at org.loadui.testfx.utils.FXTestUtils.isNodeVisible(FXTestUtils.java:253)
    at org.loadui.testfx.utils.FXTestUtils$6.apply(FXTestUtils.java:244)
    at org.loadui.testfx.utils.FXTestUtils$6.apply(FXTestUtils.java:241)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    at com.google.common.collect.Iterators.size(Iterators.java:191)
    at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:211)
    at java.util.LinkedHashSet.<init>(LinkedHashSet.java:168)
    at org.loadui.testfx.GuiTest.getVisibleNodes(GuiTest.java:232)
    at org.loadui.testfx.GuiTest.findAll(GuiTest.java:244)
    at org.loadui.testfx.GuiTest.findByCssSelector(GuiTest.java:425)
    at org.loadui.testfx.GuiTest.find(GuiTest.java:293)
```

**Comment by hastebrot** [comment]
You could try to execute `GuiTest.find()` within the JavaFX (application/user) thread. I suggesting this, because it might synchronize write calls to the JavaFX thread.

----

To investigate this further and minify the root of the problem I suggest starting with 

~~~
at org.loadui.testfx.utils.FXTestUtils.isNodeWithinSceneBounds(FXTestUtils.java:259)
~~~

which should be read-only, since it only retrieves the `Node`'s `Bounds` using

~~~
at javafx.scene.Node.getBoundsInLocal(Node.java:3131)
~~~

However we see that it also causes to call `update` methods, that do not seem to be read-only.

~~~
at javafx.scene.Node.updateGeomBounds(Node.java:3552)
at javafx.scene.Parent.updateCachedBounds(Parent.java:1584)
at javafx.scene.Node.updateTxBounds(Node.java:3616)
at javafx.scene.Node.updateGeomBounds(Node.java:3552)
...
~~~

It ends with the `ConcurrentModificationException` being thrown in

~~~
at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:386)
~~~

It would be worthwhile to investigate, what a "comodification" is this case is.

**Comment by brcolow** [comment]
Closing due to inactivity and also because this is an issue about the deprecated, unmaintained legacy version of TestFX.
