### ISSUE TITLE
IllegalArgumentException: "already set as root of another scene"

### ISSUE THREAD

**Issue by psyren89** [TestFX/TestFX#190]
Every test I run throws this error (even single tests on their own). I have googled for the longest time but found no useful information about where to look to fix this problem. I suspect it may be something to do with the `getRootNode()` method, but nothing I've tried seems to help. It currently looks like this:

```
@Override
protected Parent getRootNode() {
    try {
        if (app == null) {
            stage.centerOnScreen();
            app = new FooApplication();
            app.start(stage);
        }
        return app.getStage().getScene().getRoot();
    } catch (Exception e) {
        e.printStackTrace();
    }
    return null;
}
```

The stacktrace:

```
java.lang.IllegalArgumentException: BorderPane@498fd96c[styleClass=root]is already set as root of another scene
    at javafx.scene.Scene$9.invalidated(Scene.java:1076)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145)
    at javafx.scene.Scene.setRoot(Scene.java:1038)
    at javafx.scene.Scene.<init>(Scene.java:325)
    at javafx.scene.Scene.<init>(Scene.java:267)
    at javafx.scene.SceneBuilder.build(SceneBuilder.java:660)
    at org.loadui.testfx.GuiTest$1.run(GuiTest.java:128)
    at org.loadui.testfx.utils.FXTestUtils$4.call(FXTestUtils.java:161)
    at org.loadui.testfx.utils.FXTestUtils$4.call(FXTestUtils.java:157)
    at org.loadui.testfx.utils.FXTestUtils$3.run(FXTestUtils.java:119)
    at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
    at com.sun.javafx.application.PlatformImpl$$Lambda$53/400933581.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
    at com.sun.javafx.application.PlatformImpl$$Lambda$52/155328868.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

Running TestFX 3.1.0 (using a snapshot is not an option).

I am very new to JavaFX, and got most of my knowledge from [here](http://code.makery.ch/java/javafx-8-tutorial-intro/). Any pointers are appreciated.

**Comment by psyren89** [comment]
To clarify a little, I don't get any of these errors when building and running my app normally.

**Comment by hastebrot** [comment]
Hi Darren!

Try to replace the line

~~~java
return app.getStage().getScene().getRoot();
~~~

with

~~~java
Parent root = app.getStage().getScene().getRoot();
app.getStage().getScene().setRoot(new Region());
return root;
~~~

Explanation: After you return your root Node with "return
app.getStage().getScene().getRoot();", TestFX will try to put the root
Node into a new Scene of JavaFX's primary Stage. "app.start(stage);"
has already put your root Node into another Scene and you must not
have a root Node in two different Scenes. The work-around this issue,
we remove the root Node from the Scene, to allow TestFX to put it into
the primary Stage.

--Benjamin

**Comment by psyren89** [comment]
Excellent, that stopped the exceptions being thrown! Only problem now is the window created isn't big enough to fit everything in :neutral_face:

**Comment by psyren89** [comment]
Found a possible cause, in GuiTest, line 128:

    Scene scene = SceneBuilder.create()
        .width( 600 )
        .height( 400 )
        .root( getRootNode() ).build();

Immediately after `getRootNode()` is called, that method is run.

**Comment by pericleskb** [comment]
Have the same problem.
Has anyone found a solution?

**Comment by hastebrot** [comment]
Hey. This is a TestFX 3 issue.

Can you store the root node into a variable, set the root node of the
application's scene to null and return the variable?

**Comment by psyren89** [comment]
I solved it by doing this:
https://gist.github.com/psyren89/dec63578a32ff557e05a
and having all my test classes extend that class.

**Comment by hastebrot** [comment]
Looks nice. I totally forgot that scene always needs a node, in this case
the empty Region().

**Comment by brcolow** [comment]
Closing due to time lapsed and it appears that there is a work-around. Please let me know if there are still any remaining issues and I will re-open. Thanks!
