### ISSUE TITLE
Powermock and TestFX

### ISSUE THREAD

**Issue by Ciruman** [TestFX/TestFX#191]
Hi all,

I was trying to use TestFX to test my application. I would like to run the test for the whole application but also for some components. I used TestFX and mockito and they work great. The thing is that I wanted to mock a method of a javafx Service class that is final so I used Powermock. But using powermock it does not work any more. There is an exception:

``` java
Exception in thread "Thread-2" java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:875)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(LauncherImpl.java:157)
    at com.sun.javafx.application.LauncherImpl$$Lambda$6/77531028.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
    at com.sun.javafx.tk.quantum.QuantumToolkit.createTKStage(QuantumToolkit.java:489)
    at javafx.stage.Stage.impl_visibleChanging(Stage.java:1152)
    at javafx.stage.Window$9.invalidated(Window.java:743)
    at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
    at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:143)
    at javafx.stage.Window.setShowing(Window.java:841)
    at javafx.stage.Window.show(Window.java:856)
    at javafx.stage.Stage.show(Stage.java:255)
    at org.loadui.testfx.GuiTest$TestFxApp.start(GuiTest.java:78)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(LauncherImpl.java:821)
    at com.sun.javafx.application.LauncherImpl$$Lambda$55/1545937816.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(PlatformImpl.java:323)
    at com.sun.javafx.application.PlatformImpl$$Lambda$50/848132426.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
    at com.sun.javafx.application.PlatformImpl$$Lambda$53/930438969.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
    at com.sun.javafx.application.PlatformImpl$$Lambda$51/731363211.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$141(WinApplication.java:102)
    at com.sun.glass.ui.win.WinApplication$$Lambda$43/1673014544.run(Unknown Source)
    ... 1 more
Caused by: java.lang.NullPointerException
    at com.sun.javafx.tk.quantum.WindowStage.<clinit>(WindowStage.java:101)
    ... 23 more
```

and after a while as no scene is shown, timeout:

``` java
java.lang.RuntimeException: Unable to show stage
    at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:117)
    at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:101)
    at org.loadui.testfx.GuiTest.setupStage(GuiTest.java:91)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:132)
    at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:95)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
    at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
    at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
    at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
    at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
    at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:104)
    at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
    at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:53)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
    at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:269)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
    at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:112)
    ... 37 more

Exception in thread "Thread-2" java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:875)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(LauncherImpl.java:157)
    at com.sun.javafx.application.LauncherImpl$$Lambda$6/2121231882.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
    at com.sun.javafx.tk.quantum.QuantumToolkit.createTKStage(QuantumToolkit.java:489)
    at javafx.stage.Stage.impl_visibleChanging(Stage.java:1152)
    at javafx.stage.Window$9.invalidated(Window.java:743)
    at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
    at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:143)
    at javafx.stage.Window.setShowing(Window.java:841)
    at javafx.stage.Window.show(Window.java:856)
    at javafx.stage.Stage.show(Stage.java:255)
    at org.loadui.testfx.GuiTest$TestFxApp.start(GuiTest.java:78)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(LauncherImpl.java:821)
    at com.sun.javafx.application.LauncherImpl$$Lambda$55/1525220269.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(PlatformImpl.java:323)
    at com.sun.javafx.application.PlatformImpl$$Lambda$51/2018139689.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
    at com.sun.javafx.application.PlatformImpl$$Lambda$53/1269058336.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
    at com.sun.javafx.application.PlatformImpl$$Lambda$52/1894588467.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$141(WinApplication.java:102)
    at com.sun.glass.ui.win.WinApplication$$Lambda$43/442806334.run(Unknown Source)
    ... 1 more
Caused by: java.lang.NullPointerException
    at com.sun.javafx.tk.quantum.WindowStage.<clinit>(WindowStage.java:101)
    ... 23 more
```

Is there anyone using powermock and testfx? in case of having a final method that needs to be overridden, how are do doing it?

Thanks.
Have Fun!

**Comment by hastebrot** [comment]
Hi Ciruman,

which JavaFX method do you mock? I wonder what causes the NullPointerException.

>Is there anyone using powermock and testfx?
Nope. We use Groovy and Spock with CGlib and Objenesis, but we never
mock final methods of classes within the javafx package.

--Benjamin

**Comment by Ciruman** [comment]
And how would you mock http://docs.oracle.com/javase/8/javafx/api/javafx/concurrent/Service.html#runningProperty-- for example in case of using a service inside a controller.

For example:

```java
@Category(TestFX.class)
@RunWith(PowerMockRunner.class)
@PrepareForTest({ServiceExtendsFromJavaFXService.class})
public class TestFXTest2 extends GuiTest {

    private SimpleListProperty<DocumentViewModel> documents;

    @BeforeClass
    static public void setUpBeforeClass() throws Exception {
        System.out.println("setUpBeforeClass " + (System.currentTimeMillis()));
    }

    @Override
    protected Parent getRootNode() {
        ServiceExtendsFromJavaFXService service = PowerMockito.mock(ServiceExtendsFromJavaFXService.class);
        when(service.runningProperty()).thenReturn(new SimpleBooleanProperty(false));
        Controller controller = new Controller(service);
        return controller.getView();
    }

    @Test
    public void test() throws InterruptedException {
        //....
    }

}
```

**Comment by Ciruman** [comment]
I just happens in Windows. In Mac OS there is no problem. I also think that this is no testFX problem. I think that this is a Powermock problem. That´s why I contact powermock. :-)

Thank you!

**Comment by naimdjon** [comment]
@Ciruman  Not sure if this can help, but this is what I do in order to test a component that extends a JavaFX control:

```
package mytest;

import com.sun.javafx.application.PlatformImpl;
import com.sun.javafx.perf.PerformanceTracker;
import javafx.beans.property.SimpleStringProperty;
import javafx.scene.control.TextField;
import org.junit.Test;

import static org.fest.assertions.api.Assertions.assertThat;
import static org.junit.Assert.assertEquals;
import static org.powermock.api.mockito.PowerMockito.mockStatic;

@org.junit.runner.RunWith(org.powermock.modules.junit4.PowerMockRunner.class)
@org.powermock.core.classloader.annotations.PrepareForTest({PlatformImpl.class, PerformanceTracker.class})
public class MyAutoCompleterTest {
    private TextField textField;
    private MyAutoCompleter myAutoCompleter;

    @org.junit.Before
    public void setUp() {
        mockStatic(PlatformImpl.class, PerformanceTracker.class);
        textField = new TextField();
        myAutoCompleter = new MyAutoCompleter(textField);
    }

    @Test
    public void appends0AsSuffix() {
        myAutoCompleter.changed(new SimpleStringProperty("1234"), null, null);
        assertEquals("12340", textField.getText());
    }

    @Test
    public void doesNotAppend0AsSuffix() {
        myAutoCompleter.changed(new SimpleStringProperty("123456789 2"), null, null);
        assertThat(textField.getText()).isEmpty();
    }
}

```

**Comment by BurcuKalkan** [comment]
at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:284)
at org.testfx.api.FxToolkit.waitForLaunch(FxToolkit.java:323)
at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:132)
at org.testfx.framework.junit.ApplicationTest.internalBefore(ApplicationTest.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Native Library C:\Program Files (x86)\Java\jdk1.8.0_121\jre\bin\glass.dll already loaded in another classloader
at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:267)
at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: Native Library C:\Program Files (x86)\Java\jdk1.8.0_121\jre\bin\glass.dll already loaded in another classloader
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
at java.lang.Runtime.load0(Runtime.java:809)
at java.lang.System.load(System.java:1086)
at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:112)
at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:120)
at com.sun.glass.ui.win.WinApplication.access$300(WinApplication.java:39)
at com.sun.glass.ui.win.WinApplication$1.run(WinApplication.java:118)
at com.sun.glass.ui.win.WinApplication$1.run(WinApplication.java:91)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.glass.ui.win.WinApplication.(WinApplication.java:91)
at com.sun.glass.ui.win.WinPlatformFactory.createApplication(WinPlatformFactory.java:39)
at com.sun.glass.ui.win.WinPlatformFactory.createApplication(WinPlatformFactory.java:36)
at com.sun.glass.ui.Application.run(Application.java:146)
at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
... 5 more

I get this error when I run my all tests together. I searched I try a lot of thing but I couldn't solve the problem. AlertMessagesTest is passed but when test comes to ItineraryControllerTest class it gives this exception. Could anybody help me please?
public class AlertMessagesTest extends TestFXGuiBase{
@test
public void setMessage() throws Exception {
Platform.runLater(() -> AlertMessages.setMessage(AlertMessages.AlertMessagesType.NAME, ""));
functions.sleep(1000);
functions.clickOn("Tamam");
}
@test
public void isEqual() throws Exception {
Platform.runLater(() -> AlertMessages.isEqual(AlertMessages.AlertMessagesType.NOT_EQUAL_PASSWORD, "1", "2"));
functions.sleep(1000);
functions.clickOn("Tamam");
}
@test
public void isRange() throws Exception {
Platform.runLater(() -> AlertMessages.isRange(AlertMessages.AlertMessagesType.IDENTIFICATION_NUMBER, 1, 2,5));
functions.sleep(1000);
functions.clickOn("Tamam");
}
@beforeclass
public static void beforeClass() throws Exception{
FxToolkit.registerPrimaryStage();
}
@afterclass
public static void afterClass() throws Exception{
FxToolkit.hideStage();
}
@override
public void start(Stage stage) throws Exception {
}
}

@runwith(PowerMockRunner.class)
@preparefortest( {Database.class, AlertManager.class, ItineraryListController.class} )
public class ItineraryControllerTest extends TestFXGuiBase{

FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/fxml/itineraryManagement/addItinerary.fxml"));

@Override
public void start(Stage stage) throws Exception {
    Parent root = fxmlLoader.load();
    Scene scene = new Scene(root);
    stage.setScene(scene);
    stage.show();
}

@Test
public void addItinerarySuccessTestFunction() throws Exception{
 }
}

I found the reason @runwith(PowerMockRunner.class). when I remove it dll exception is removed but this time no last call on a mock available exception thrown. But I don't found the solution yet. TestFx and powermockito using gives this exception

**Comment by brcolow** [comment]
Closing due to inactivity and because I have no experience with Powermock.
