### ISSUE TITLE
TestFX 4.0.1 and travis

### ISSUE THREAD

**Issue by sven4all** [TestFX/TestFX#220]
Does anyone know how to configure travis so that it can run testcases that uses testfx? I get constantly this exception:

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Location is not set.

For the log see:
https://travis-ci.org/Hansschouten/context_health_informatics/jobs/63465960 (line 1822)

For the source:
https://github.com/Hansschouten/context_health_informatics/tree/travis_gui

**Comment by hastebrot** [comment]
Seems to be an error related to an FXML file:

~~~java
Caused by: java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2428)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2403)
	at controller.MainApp.initRootLayout(MainApp.java:65)
	at controller.MainApp.start(MainApp.java:54)
~~~

**Comment by sven4all** [comment]
Strange locally it works fine, I will have a look.
