### ISSUE TITLE
Fullscreen Support

### ISSUE THREAD

**Issue by falkoschumann** [TestFX/TestFX#235]
Is fullscreen mode supported? If I set `primaryStage.setFullScreen(true)` in `Application::start()` then `FxToolkit.setupApplication(...)` throws a `TimeoutException`. Without fullscreen the test run successfully.

**Comment by hastebrot** [comment]
Hi Falko,

here [1] is a working SSCCE that uses `stage.setFullScreen(true)`. I thought you missed `stage.show()`, but this does not explain why your test succeed without fullscreen.

[1] https://github.com/TestFX/TestFX-Playground/blob/7c35dbd6a6/projects/testfx-playground/src/test/java/org/testfx/playground/issue/github_235_fullscreen.java

**Comment by falkoschumann** [comment]
The example does not work. I run the unit test within IntelliJ IDEA and Eclipse. Both I get an TimeoutException at `FxToolkit.setupApplication(FullScreenApp.class);`. If change fullscreen to false, it runs.

I use Java 8 Update 45 and TestFX 4.0.1-alpha under OS X. What is your test environment.

**Comment by hastebrot** [comment]
Windows 7. I assume this is the issue with OS X we had in #121 which was fixed with #126. The regression seems to be introduced with #137.

Could you try to initialize the JavaFX toolkit with the lines in this order?

~~~java
System.setProperty("java.awt.headless", "false");
FxToolkit.registerPrimaryStage();
~~~

**Comment by falkoschumann** [comment]
It does not work. But I can successful run fullscreen in headless mode with:

    System.setProperty("java.awt.headless", "false");
    System.setProperty("testfx.robot", "glass");
    System.setProperty("testfx.headless", "true");
    FxToolkit.registerPrimaryStage();

But in non-headless the fullscreen does not work.

**Comment by falkoschumann** [comment]
I tested the example with Windows 7. It works here also. So it is probably a problem with OS X.

**Comment by hastebrot** [comment]
Seems to be a bug in the OS X port of JavaFX. I have an old virtual machine
with OS X here, but the JDK version ist 6u5 and core dumps consistently. I
cannot update the JDK because my internet connection via mobile to test
this further.

**Comment by hastebrot** [comment]
Worth testing: In `ApplicationLauncherImpl` the property "javafx.macosx.embedded" is set to "true". You can overwrite it using (TestFX will recognize, that the property is already set):

~~~
System.setProperty("javafx.macosx.embedded", "false");
FxToolkit.registerPrimaryStage();
~~~

**Comment by falkoschumann** [comment]
No change. Still a time out exception. Here is the stack trace:

    java.util.concurrent.TimeoutException: Timeout waiting for task.
    
    	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:269)
    	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
    	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:144)
    	at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:291)
    	at org.testfx.api.FxToolkit.setupApplication(FxToolkit.java:165)
    	at org.testfx.playground.issue.github_235_fullscreen.setup(github_235_fullscreen.java:28)
