### ISSUE TITLE
(bug) Cleanup hangs when FX Application Thread got killed

### ISSUE THREAD

**Issue by Ortner** [TestFX/TestFX#287]
## Issue
The Cleanup is called in the `after` method of JUnit tests. If the FX Application Thread is beeing killed during the test, the call to the clean up method `cleanupApplication()` in `FXToolkit` waiting for the cleanup to be performed on the FX Application Thread.

## Solution
Detect, if the Application thread is running, before doing the cleanup.

**Comment by hastebrot** [comment]
In general the FX Thread is killed by using `Platform.exit()`, which is also implicitely called when the last `Window` or `Stage` was closed (TestFX prevents this by using `Platform.setImplicitExit(false)`).

I think the easiest way it to retrieve the FX Thread from `Set<Thread> threadSet = Thread.getAllStackTraces().keySet();`, check if it is running, otherwise throw an exception.

**Comment by hastebrot** [comment]
Oh, you already implemented it. :+1:

**Comment by Ortner** [comment]
Yes. I do cancel the future, so feedback is passed this way.

I do have the problem, with headless tests. If the Platform has an exception during start up:
```
java.lang.ClassNotFoundException: com.sun.glass.ui.monocle.MonoclePlatformFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
```
It hangs up during cleanup, as JUnit tears down after the Exception.

Using frambuffer on my build server it also hangs (not on my machine with the same docker image?!).

**Comment by mjmaix** [comment]
thanks ortner this helped me

**Comment by Ortner** [comment]
Oh, thanks for the feedback. Always good to hear, that this fix helps others too.
