### ISSUE TITLE
Intermittent unit test failures -- TimeoutException

### ISSUE THREAD

**Issue by ZeLonewolf** [TestFX/TestFX#367]
Hello!

In my JUnit tests that use testFx, I have these exceptions that appear from time to time that originate from within testFx.  This occurs intermittently.  What should I be looking for to solve this?

```
java.util.concurrent.TimeoutException: java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:432)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:157)
	at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:331)
	at org.testfx.api.FxToolkit.setupApplication(FxToolkit.java:198)
	at org.testfx.framework.junit.ApplicationTest.internalBefore(ApplicationTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by brcolow** [comment]
If you can create a self-contained test project that shows the failure, even if it only fails intermittently as you say, I will be able to help further. Unfortunately I can not answer about what you should be looking for to solve this without more information.

**Comment by ZeLonewolf** [comment]
Ugh.  The problem is that this seems to only occur on a handful of my more complex tests (same stack trace every time), and because the stack trace doesn't ever enter my code I don't even know where to begin to start to narrow this down to a reasonable test project.

**Comment by brcolow** [comment]
I just want to make sure that you are using the latest released version, 4.0.5-alpha, because some exception handling masking was fixed recently?

**Comment by ZeLonewolf** [comment]
Yes, I am using:
org.testfx:testfx-core:4.0.5-alpha
org.testfx:testfx-junit:4.0.5-alpha

I was using 4.0.1 and upgraded to 4.0.5 before making this post in the hopes that it would make my issue go away.

**Comment by brcolow** [comment]
Would it be possible for you to just copy the source code of one of the tests that fail? Doesn't have to be a self-contained project as I stated, just one of the failing tests will help immensely.

**Comment by ZeLonewolf** [comment]
The problem is that the problem tests are complex integration tests that start the Spring Framework and drag in large chunks of my application.  I started to try to separate that test case with all of its dependency and it was so big it wasn't feasible to do.  So I know you want a definitive test case to demonstrate but I can't reasonably make it.  I was hoping that the stack trace above would be able to give me some kind of targetted clue as to what I'm doing wrong.

**Comment by brcolow** [comment]
I don't see how the stack-trace you posted can possibly be from the latest version:

https://github.com/TestFX/TestFX/blob/1f1956a40a79d645992981acf5272116a3f19e30/subprojects/testfx-core/src/main/java/org/testfx/util/WaitForAsyncUtils.java#L157

**Comment by carltonwhitehead** [comment]
I've seen a similar stack trace, but only on a Travis CI Mac worker. I re-ran the same build a few times and eventually it passed. I haven't seen this timeout occur on a fast laptop nor on a Travis CI Linux worker.

Unfortunately, Travis seems to have overwritten the failure log when the job eventually passed. I recall seeing in one of the failure logs that the error occurred during the first test class that it tried to execute. The second test class worked fine. Both classes extended `org.testfx.framework.junit.ApplicationTest` and carried out very simple tests against a very simple UI.

I wonder if the argument suggested for the Travis CI Mac worker `-Dtestfx.setup.timeout=2500` from [How to Use with Continuous Integration](https://github.com/TestFX/TestFX/wiki/How-to-Use-with-Continuous-Integration) could be influencing it. I'm going to raise that and see if it helps.

**Comment by brcolow** [comment]
I have also used [TestFXRule](https://github.com/TestFX/TestFX/blob/master/subprojects/testfx-junit/src/main/java/org/testfx/framework/junit/TestFXRule.java) to wait for JavaFX initialization as well as retry failing tests. It's really not ideal but it does seem to work. Having a surefire way to verify that the JavaFX platform has been initialized before the first test would be nice.

**Comment by dmusican** [comment]
FYI, I'm seeing a similar bug on occasion in a non-repeatable way on a Travis CI Linux VM. Thanks for the info on `TestFXRule`; I've added it to all of my tests in hopes that it will help. It seems that it certainly can't hurt.

**Comment by eoliverio** [comment]
I have the exact same stack trace in version 4.0.15
Also tried adding the TestFXRule but the error still _intermittently_ persists,
Does anybody have any kind of workaround?
