### ISSUE TITLE
TimeoutException occurs at the end of test execution

### ISSUE THREAD

**Issue by aalmiray** [TestFX/TestFX#369]
I'm consistently getting `TimeoutException` at the end of the following test

    package griffon.javafx.scene.layout

    import javafx.event.ActionEvent
    import javafx.event.EventHandler
    import javafx.scene.Node
    import javafx.scene.Scene
    import javafx.scene.control.Button
    import javafx.scene.control.ButtonBar
    import javafx.scene.control.Label
    import javafx.scene.layout.BorderPane
    import javafx.scene.layout.StackPane
    import javafx.stage.Stage
    import org.junit.Test
    import org.testfx.framework.junit.ApplicationTest
    import org.testfx.service.support.WaitUntilSupport

    import java.util.concurrent.Callable

    import static org.hamcrest.MatcherAssert.assertThat
    import static org.hamcrest.Matchers.equalTo
    import static org.testfx.api.FxAssert.verifyThat
    import static org.testfx.matcher.base.NodeMatchers.isVisible

    class NamedCardPaneTest extends ApplicationTest {
        @Override
        void start(Stage stage) throws Exception {
            BorderPane borderPane = new BorderPane()
            ButtonBar buttonBar = new ButtonBar()
            borderPane.setTop(buttonBar)
            NamedCardPane cardPane = new NamedCardPane()
            cardPane.setId('cardPane')
            borderPane.setCenter(cardPane)

            1.upto(5) { i ->
                Label card = new Label('Card ' + i)
                String id = 'card_' + i
                StackPane stack = new StackPane(card)
                stack.setId(id)
                cardPane.getChildren().add(stack)

                Button b = new Button(id)
                b.setOnAction({ cardPane.show(id) } as EventHandler<ActionEvent>)
                buttonBar.getButtons().add(b)
            }

            Scene scene = new Scene(borderPane)
            stage.setScene(scene)
            stage.show()
        }

        @Test
        void browseCards() {
            // given:
            WaitUntilSupport waiter = new WaitUntilSupport()
            NamedCardPane cardPane = lookup('#cardPane').query()
            cardPane.show('card_5')

            5.downto(1) { i ->
                // when:
                clickOn('card_' + i)

                // then:
                waiter.waitUntil({ cardPane.getSelectedNodeId() } as Callable, equalTo('card_' + i), 1)
                verifyThat('Card ' + i, isVisible())
            }
        }
    }

The exception is 

    java.util.concurrent.TimeoutException: FX Application Thread not running
        at org.testfx.api.FxToolkit.cleanupApplication(FxToolkit.java:220)
        at org.testfx.framework.junit.ApplicationTest.internalAfter(ApplicationTest.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
        at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Running with TestFX 4.0.5-alpha, Spock 1.0.
There's a second test with a different component that fails in the same way.

Any clues on what may be causing the problem?

**Comment by hastebrot** [comment]
Hi Andres!

~~~
java.util.concurrent.TimeoutException: FX Application Thread not running
    at org.testfx.api.FxToolkit.cleanupApplication(FxToolkit.java:220)
    at org.testfx.framework.junit.ApplicationTest.internalAfter(ApplicationTest.java:67)
~~~

I guess something stopped the JavaFX thread.

**Comment by aalmiray** [comment]
That appears to be the case however there's no code in the custom component nor the test that hints to that. As an aside, wouldn't it be good if `WaitUntilSupport` be merged into `FxRobot`? I find it a bit wonky to have to instantiate `WaitUntilSupport` instead of just calling methods in the testcase itself. WDYT?

**Comment by hastebrot** [comment]
>As an aside, wouldn't it be good if WaitUntilSupport be merged into FxRobot?

Definitely. There are some open questions concerning the API in #218 and #242.

**Comment by hastebrot** [comment]
>That appears to be the case however there's no code in the custom component nor the test that hints to that.

To identify the cause, could you replace `NamedCardPane` with e.g. `StackPane` and rerun the test? We have a starting point for investigation if the tests fail without the `TimeoutException`.

**Comment by aalmiray** [comment]
I made some experiments, such as

 . running the original test code in a separate build: OK.
 . running the NamedCardPaneTest in isolation (single test): OK.

It looks like there are other JavaFX related tests found under  `griffon.javafx` that are causing trouble. These tests do not depend on TestFX in any way. there is indeed some leakage somewhere that's affecting TestFX in a weird way. We'll keep looking and let you know.

**Comment by aalmiray** [comment]
Turns out forking the test process "fixes" the problem even though I still don't know what the actual problem is. Other tests do not rely on the FX UI thread to be up.

**Comment by brcolow** [comment]
Thanks for keeping us up-to-date. Do you think it's a problem on our end or yours?

**Comment by aalmiray** [comment]
I don't think TestFX is to blame here. Haven't found the actual cause of the problem yet.
