### ISSUE TITLE
Thread main blocked indefinitely

### ISSUE THREAD

**Issue by Gabun** [TestFX/TestFX#401]
Hi,
Just started using TestFX and I encountered a problem with the main thread blocked forever. Tried to used openjfx-monocle to set System.setProperty("testfx.robot", "glass"); but this didn't solve the issue, but at list the clickOn method does return now. The problem ocures when using clickOn on a modal dialog that uses showAndWait.

By using System.setProperty("testfx.robot", "glass"); I get the clickOn to return and the @After public void cleanUp() to exceture. But the main thread still blockes waiting for the event.

By the way I don't know why but by default the AwtRobotAdapter implementation was used and the clickOn never returned.

When it does not hang I get the following error:

Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = JavaFX Application Thread
	at com.sun.glass.ui.Application.checkEventThread(Application.java:443)
	at com.sun.glass.ui.Application.isNestedLoopRunning(Application.java:544)
	at com.sun.javafx.tk.quantum.QuantumToolkit.isNestedLoopRunning(QuantumToolkit.java:1139)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:585)
	at javafx.stage.Stage.showAndWait(Stage.java:474)
	at com.something.showErrorDialog(Main.java:215)
	at com.something.start(Main.java:77)
	at com.something.lambda$0(MainTest5.java:104)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

Tried to put everything in Platform.runLater but the error persists and the thread still blocks.

![screenshot_9](https://user-images.githubusercontent.com/3983700/27338848-882c3a24-55d6-11e7-9bb6-e999e948783e.png)
![screenshot_10](https://user-images.githubusercontent.com/3983700/27338863-8e5130da-55d6-11e7-8071-556e7d87fdf0.png)

I tried all day to fix this problem but was not succesfull. 

Test class: code

```
 @Rule
  public PowerMockRule rule = new PowerMockRule();

  static {
    System.setProperty("testfx.robot", "glass");
    System.setProperty("prism.order", "sw");
    System.setProperty("prism.text", "t2k");
    PowerMockAgent.initializeIfNeeded();
  }

/*
* Code in  @Before mocking some classes (I can not share this part of the test, could edit it a bit)
*/

 @Override
  public void start(Stage stage) throws IOException {
    testStage = stage;
    Platform.runLater(() -> {

      Main wm = new Main ();
      wm.start(stage);
    });
    stage.setOnCloseRequest(windowEvent -> System.out.println(windowEvent));
    stage.show();
  }

  /**
   * Test.
   */
  @Test
  public void test() {
    System.out.println("Test!");
    Platform.runLater(() -> {
      Node node = ReflexionUtil.searchFxNode(this, "#btnErrorOk");
      System.out.println("Calling click");
      clickOn(node,Motion.DIRECT, MouseButton.PRIMARY);
      System.out.println("Click done");
    });
  }

  @After
  public void afterClassTest() throws Exception {
    Platform.runLater(() -> {
      Platform.exit();
    });
    
  }
```

Thank you in advanced.

**Comment by brcolow** [comment]
Too much missing code/complex interactions for me to properly diagnose the problem.
