### ISSUE TITLE
Java 8: Exception "Not on FX application thread" in TextInputControlsTest

### ISSUE THREAD

**Issue by hastebrot** [TestFX/TestFX#41]
Ran all tests from IntelliJ IDEA 13 on Windows 7 (x64). Throws this exception with Java build 1.8.0-ea-b120 (x64), but runs without exception with Java build 1.7.0_45-b18 (x64).

```
java.lang.IllegalStateException: Not on FX application thread; currentThread = main
    at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:210)
    at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:393)
    at javafx.scene.Scene.addToDirtyList(Scene.java:521)
    at javafx.scene.Node.addToSceneDirtyList(Node.java:417)
    at javafx.scene.Node.impl_markDirty(Node.java:408)
    at javafx.scene.shape.Shape.impl_markDirty(Shape.java:930)
    at javafx.scene.Node.impl_geomChanged(Node.java:3758)
    at javafx.scene.text.Text.impl_geomChanged(Text.java:772)
    at javafx.scene.text.Text.needsTextLayout(Text.java:202)
    at javafx.scene.text.Text.needsFullTextLayout(Text.java:197)
    at javafx.scene.text.Text.access$400(Text.java:96)
    at javafx.scene.text.Text$4.invalidated(Text.java:396)
    at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
    at javafx.beans.property.StringPropertyBase.access$000(StringPropertyBase.java:49)
    at javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:229)
    at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:135)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    at javafx.beans.binding.StringBinding.invalidate(StringBinding.java:171)
    at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51)
    at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:339)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1116)
    at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1120)
    at javafx.scene.control.TextInputControl$TextProperty.invalidate(TextInputControl.java:1060)
    at javafx.scene.control.TextInputControl$TextProperty.access$200(TextInputControl.java:1032)
    at javafx.scene.control.TextInputControl$1.invalidated(TextInputControl.java:130)
    at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:135)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
    at javafx.scene.control.TextField$TextFieldContent.delete(TextField.java:91)
    at javafx.scene.control.TextInputControl$TextProperty.doSet(TextInputControl.java:1128)
    at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1055)
    at javafx.scene.control.TextInputControl.setText(TextInputControl.java:279)
    at javafx.scene.control.TextInputControl.clear(TextInputControl.java:925)
    at org.loadui.testfx.controls.TextInputControls.clearTextIn(TextInputControls.java:24)
    at org.loadui.testfx.TextInputControlsTest.shouldClearText(TextInputControlsTest.java:32)
```

**Comment by xyqjay817** [comment]
发电公司大法官

**Comment by xyqjay817** [comment]
你们这些智障。
