### ISSUE TITLE
Deflake flaky tests

### ISSUE THREAD

**Issue by JordanMartinez** [TestFX/TestFX#411]
As stated in #404, compile a list of flaky tests and get rid of them. That PR could have been merged much earlier but wasn't due to flaky tests. Removing this bottleneck should speed up development for future PRs.

**Comment by JordanMartinez** [comment]
## Windows (only appears to be 1 flaky test)
- org.testfx.cases.acceptance.FxAssertBasicTest > button_has_label FAILED
   - [Headed - master 310](https://ci.appveyor.com/project/testfx/testfx/build/master%20310/job/35svwog76qlbpy6m#L1082)
   - [Headless - master 309](https://ci.appveyor.com/project/testfx/testfx/build/master%20309/job/8ri3u6qdxeqphhba#L1082)
````
    java.lang.AssertionError: 
    Expected: Node has text "clicked!"
         but: was <Button[id=button, styleClass=root button]'click me!'>
        at org.testfx.api.FxAssert.verifyThatImpl(FxAssert.java:150)
        at org.testfx.api.FxAssert.verifyThat(FxAssert.java:84)
        at org.testfx.cases.acceptance.FxAssertBasicTest.button_has_label(FxAssertBasicTest.java:99)
````

**Comment by JordanMartinez** [comment]
## OSX (1 Full Headless; 7 Partial Headless)

Where "___ Headless" is based on the environment variables
````json
# Full Headless
"env": "_JAVA_OPTIONS=\"-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500\""
# Partial Headless
"env": "OSX_HEADLESS=false _JAVA_OPTIONS=\"-Dprism.order=sw\""
````
- Full Headless - [org.testfx.service.finder.impl.WindowFinderImplTest STANDARD_ERROR](https://travis-ci.org/TestFX/TestFX/jobs/262166281#L4662)
````
    Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    	at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:402)
    	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:511)
    	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
    	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
    	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
    	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
    	at java.lang.Thread.run(Thread.java:745)
````
- Partial Headless - [org.testfx.cases.acceptance.FxAssertBasicTest > button_has_label FAILED](https://travis-ci.org/TestFX/TestFX/jobs/262166284#L3842)
````
    java.lang.AssertionError: 
    Expected: Node has text "clicked!"
         but: was <Button[id=button, styleClass=root button]'click me!'>
        at org.testfx.api.FxAssert.verifyThatImpl(FxAssert.java:150)
        at org.testfx.api.FxAssert.verifyThat(FxAssert.java:84)
        at org.testfx.cases.acceptance.FxAssertBasicTest.button_has_label(FxAssertBasicTest.java:99)
````
- Partial Headless - [org.testfx.cases.integration.DragAndDropTest > should_drag_and_drop_from_right_to_left FAILED](https://travis-ci.org/TestFX/TestFX/jobs/262166284#L3963)
````
    java.lang.AssertionError: 
    Expected: iterable containing ["L1", "L2", "L3", "R3"]
         but: No item matched: "R3"
        at org.testfx.api.FxAssert.verifyThatImpl(FxAssert.java:150)
        at org.testfx.api.FxAssert.verifyThat(FxAssert.java:62)
        at org.testfx.cases.integration.DragAndDropTest.should_drag_and_drop_from_right_to_left(DragAndDropTest.java:116)
````
- Partial Headless - [org.testfx.cases.integration.DragAndDropTest > should_drag_and_drop_from_left_to_right FAILED](https://travis-ci.org/TestFX/TestFX/jobs/262166284#L3978)
````
    java.lang.AssertionError: 
    Expected: iterable containing ["L2", "L3"]
         but: item 0: was "L1"
        at org.testfx.api.FxAssert.verifyThatImpl(FxAssert.java:150)
        at org.testfx.api.FxAssert.verifyThat(FxAssert.java:62)
        at org.testfx.cases.integration.DragAndDropTest.should_drag_and_drop_from_left_to_right(DragAndDropTest.java:104)
````
- Partial Headless - [org.testfx.cases.integration.MenuBarTest > should_move_vertically_first FAILED](https://travis-ci.org/TestFX/TestFX/jobs/262166284#L3990)
````
    org.testfx.api.FxRobotException: the query "#newItem" returned no nodes.
        at org.testfx.api.FxRobot.queryVisibleNode(FxRobot.java:1107)
        at org.testfx.api.FxRobot.pointOfVisibleNode(FxRobot.java:1076)
        at org.testfx.api.FxRobot.clickOn(FxRobot.java:750)
        at org.testfx.api.FxRobot.clickOn(FxRobot.java:60)
        at org.testfx.cases.integration.MenuBarTest.should_move_vertically_first(MenuBarTest.java:101)
````
- Partial Headless - [org.testfx.matcher.control.ComboBoxMatchersTest > hasSelection FAILED](https://travis-ci.org/TestFX/TestFX/jobs/262166284#L4198)
````
    java.lang.AssertionError: 
    Expected: ComboBox has selection bob
         but: was <ComboBox@2427a0da[styleClass=combo-box-base combo-box]>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.testfx.matcher.control.ComboBoxMatchersTest.hasSelection(ComboBoxMatchersTest.java:84)
````
- Partial Headless - [org.testfx.robot.impl.ShortcutKeyTest > shortcut_keyCode_converts_to_OS_specific_keyCode_when_pressed FAILED](https://travis-ci.org/TestFX/TestFX/jobs/262166284#L4564)
````
    java.lang.AssertionError: 
    Expected: "pressed"
         but: was ""
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.testfx.robot.impl.ShortcutKeyTest.shortcut_keyCode_converts_to_OS_specific_keyCode_when_pressed(ShortcutKeyTest.java:95)
`````
- Partial Headless - [org.testfx.robot.impl.ShortcutKeyTest > shortcut_keyCode_converts_to_OS_specific_keyCode_when_released FAILED](https://travis-ci.org/TestFX/TestFX/jobs/262166284#L4574)
````
    java.lang.AssertionError: 
    Expected: "pressed"
         but: was ""
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.testfx.robot.impl.ShortcutKeyTest.shortcut_keyCode_converts_to_OS_specific_keyCode_when_released(ShortcutKeyTest.java:104)
````

**Comment by JordanMartinez** [comment]
Linux
- ENV irrelevant: JDK 8 build fails due to trying to install JDK 9 (why are we installing 9 on the 8 build?) due to using weak SHA1 signature
   - ["USE_FRAMEBUFFER" version](https://travis-ci.org/TestFX/TestFX/jobs/260120002#L525)
   - [Headless version](https://travis-ci.org/TestFX/TestFX/jobs/260120004#L525)
- [JDK 9 build fails due using weak SHA1 signature](https://travis-ci.org/TestFX/TestFX/jobs/260120007#L525)

**Comment by JordanMartinez** [comment]
Not sure if this is an issue.... but if a test fails, the `releaseKey/MouseButton` code never runs

**Comment by JordanMartinez** [comment]
Using the build from #422, it seems like an OSX - Partial Headless test is failing but the AssertionError is not being thrown properly. [Looking at this test](https://travis-ci.org/TestFX/TestFX/jobs/268541522#L3954), it indicates that the second test to run is also the second test to fail. It should say "tesfx-test - 0.png", but the number is 1, not 0.

Likewise, the DragAndDropTest marks the number at 8 ([see here](https://travis-ci.org/TestFX/TestFX/jobs/268541522#L4210)), passes through a few unfailed tests, and reports it again at 11 ([see here](https://travis-ci.org/TestFX/TestFX/jobs/268541522#L4479)). @brcolow Any idea why that is happening?

**Comment by JordanMartinez** [comment]
Here's why the menu bar test doesn't work:

![mbi](https://user-images.githubusercontent.com/8413037/29736948-598f4742-89bb-11e7-8ef9-8a813d6717f4.gif)

**Comment by JordanMartinez** [comment]
While I was working on #429, I came across a situation during the `gradle build` process: content that I had stored in my clipboard was pasted into my IDE, the underlying window, when the tests were running. I'm not sure what caused it or why, but I thought it'd be worth mentioning here.

**Comment by brcolow** [comment]
Closing for now as things have changed quite a bit. There are still test failures and general flakiness, but a combination of retrying tests (via a JUnit rule) and longer setup timeouts seem to have made things much better.
