### ISSUE TITLE
RejectedExecutionException after running tests

### ISSUE THREAD

**Issue by higgs01** [TestFX/TestFX#479]
Hello

After running my FXTests, I sometimes get the following exception:
```
java.util.concurrent.RejectedExecutionException: Task com.sun.javafx.tk.quantum.PaintRenderJob@7860a6f6 rejected from com.sun.javafx.tk.quantum.QuantumRenderer@6e17239b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1634]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.sun.javafx.tk.quantum.QuantumRenderer.submitRenderJob(QuantumRenderer.java:218)
	at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:452)
	at com.sun.javafx.tk.quantum.ViewScene.repaint(ViewScene.java:140)
	at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:435)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:511)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
````
### Steps to reproduce
I couldn't find a way to reproduce it, and it doesn't always occur.

### Prequesites
FXTest version: 3.1.2
JDK: 1.8.0_144
OS: Windows 10

**Comment by brcolow** [comment]
I believe this is not a problem (it is not causing any tests to fail, correct?) and is related to how JavaFX is shutdown.

**Comment by higgs01** [comment]
No, tests don't fail. It just wasn't clean and I was a bit worried.
As you say it is from JavaFX and not from FXTest i'll close this issue.

**Comment by brcolow** [comment]
TestFX 4 doesn't have this issue because we manually filter out such exceptions.
