### ISSUE TITLE
Headless issues

### ISSUE THREAD

**Issue by RoiEXLab** [TestFX/TestFX#494]
Hi, I'm new to this framework and I had a hard time getting used to  it, because of lacking documentation, so excuse me if I'm missing something obvious (using JUnit 5 btw.).
If I understand this correctly, Headless mode is not the default mode and optional.
This leads to the following issues (at least for me):
Headless mode is required for my project (for travis builds at least, because nobody wants to fiddle around with travis settings, just to make a framework work), so I came up with the following workaround:
```java
public MainMenuPaneTest() {
  System.setProperty("java.awt.headless", String.valueOf(true));
  System.setProperty("testfx.robot", "glass");
  System.setProperty("testfx.headless", String.valueOf(true));
  System.setProperty("prism.order", "sw");
  System.setProperty("prims.text", "t2k");
}
```
I wrote a custom constructor that initializes the System variables to execute TestFX in Headless mode: This worked fine for a ubuntu headless client but then the next error came up:
```
java.lang.RuntimeException: java.lang.IllegalStateException: Monocle headless platform not found
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:337)
	at org.testfx.api.FxToolkit.waitForLaunch(FxToolkit.java:325)
	at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:134)
	at org.testfx.framework.junit5.ApplicationExtension.beforeEach(ApplicationExtension.java:79)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$null$0(TestMethodTestDescriptor.java:126)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:152)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:125)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:104)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:83)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:82)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
	Suppressed: java.util.concurrent.TimeoutException: FX Application Thread not running
		at org.testfx.api.FxToolkit.cleanupApplication(FxToolkit.java:223)
		at org.testfx.framework.junit5.ApplicationExtension.afterEach(ApplicationExtension.java:85)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$null$11(TestMethodTestDescriptor.java:214)
		at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:226)
		at java.util.ArrayList.forEach(ArrayList.java:1257)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:224)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:213)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:116)
		... 43 more
Caused by: java.lang.IllegalStateException: Monocle headless platform not found
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.initMonocleHeadless(ApplicationLauncherImpl.java:74)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.launch(ApplicationLauncherImpl.java:53)
	at org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupPrimaryStage$0(ToolkitServiceImpl.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.testfx.util.WaitForAsyncUtils$ASyncFXCallable.call(WaitForAsyncUtils.java:729)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sun.glass.ui.monocle.MonoclePlatformFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.assignMonoclePlatform(ApplicationLauncherImpl.java:90)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.initMonocleHeadless(ApplicationLauncherImpl.java:70)
	... 9 more
```
The error seems pretty obvoius, and I found your Monocle repository, but how am I supposed to install this dependency? I haven't found any documentation on this.
So in this case I need to change my custom constructor to this:
```java
public MainMenuPaneTest() {
  try {
    // Check if class exists
    Class.forName("com.sun.glass.ui.monocle.MonoclePlatformFactory");
    // Class exists, continue in Headless Mode
    System.setProperty("java.awt.headless", String.valueOf(true));
    System.setProperty("testfx.robot", "glass");
    System.setProperty("testfx.headless", String.valueOf(true));
    System.setProperty("prism.order", "sw");
    System.setProperty("prims.text", "t2k");
  } catch (ClassNotFoundException e) {
    // Fall back to Headed Java
  }
}
```
But this code got really ugly by now. I'd have to do this for every Test class I create, and I depend on Reflection that might change with an update of Java.

So now I'm wondering: Why doesn't TestFX handle this for me and others automatically?
Why can't the ApplicationExtension just perform this check on it's own?
Adding a second extension for this kind of tests wouldn't bee too hard either, if you disagree that this should be the default behaviour.

Also you should probably mention how to enable headless mode somewhere in your documentation, I found this whe it was mentioned in one of your issues, not in the README, not in the JUnit 5 Test class (which even has an issue, because the method annotated with `@Start` needs to be public)

**Comment by brcolow** [comment]
Are you using Maven or Gradle? The monocle dependency can be added as any other library. If you are not using a build system it is more complicated.

I probably messed up the visibility modifier on the JUnit 5 test class, sorry about that. If you would be so kind as to open a PR that fixes it I would greatly appreciate it.

In terms of making TestFX operate in headless mode on Travis CI, we use the following config in our `.travis.yml`:

```yaml
  # Ubuntu Linux (trusty) / Java 8 / Headless
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
```

This sets the VM options so it is not necessary to specify them for each test. Exactly how you set the VM options will depend on if you are using Maven or Gradle (or nothing in which case you will have to explicitly add them to your JVM invocation).

Next, in order to get Headed mode working on Travis CI all that should be necessary is the following in your `.travis.yml`:

```yml
before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi
```

Finally, I know the documentation is almost non-existent and I apologize for that. I am trying to do as much as I can since I have taken over maintaining the project. If you are helped by me in this issue, maybe you could return the favor and add a PR for improved documentation 😄 ?

**Comment by RoiEXLab** [comment]
We at @triplea-game use gradle for building.
Thanks for your guide, you should consider adding it to the README 😄 
I'll see what I can do once I get used to the framework and have used it for a while  👍

**Comment by RoiEXLab** [comment]
@brcolow Any chance you could tell me an artifact name on jcenter or maven central for the monocle dependency?

**Comment by brcolow** [comment]
https://mvnrepository.com/artifact/org.testfx/openjfx-monocle
