### ISSUE TITLE
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Native Library C:\Program Files (x86)\Java\jdk1.8.0_121\jre\bin\glass.dll already loaded in another classloader

### ISSUE THREAD

**Issue by BurcuKalkan** [TestFX/TestFX#505]
at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:284)
	at org.testfx.api.FxToolkit.waitForLaunch(FxToolkit.java:323)
	at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:132)
	at org.testfx.framework.junit.ApplicationTest.internalBefore(ApplicationTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Native Library C:\Program Files (x86)\Java\jdk1.8.0_121\jre\bin\glass.dll already loaded in another classloader
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: Native Library C:\Program Files (x86)\Java\jdk1.8.0_121\jre\bin\glass.dll already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFullPath(NativeLibLoader.java:201)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:94)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
	at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:112)
	at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:120)
	at com.sun.glass.ui.win.WinApplication.access$300(WinApplication.java:39)
	at com.sun.glass.ui.win.WinApplication$1.run(WinApplication.java:118)
	at com.sun.glass.ui.win.WinApplication$1.run(WinApplication.java:91)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.win.WinApplication.<clinit>(WinApplication.java:91)
	at com.sun.glass.ui.win.WinPlatformFactory.createApplication(WinPlatformFactory.java:39)
	at com.sun.glass.ui.win.WinPlatformFactory.createApplication(WinPlatformFactory.java:36)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	... 5 more

# **I get this error when I run my all tests together. I searched I try a lot of thing but I couldn't solve the problem. AlertMessagesTest is passed but when test comes to ItineraryControllerTest class it gives this exception. Could anybody help me please?**

public class AlertMessagesTest extends TestFXGuiBase{
    @Test
    public void setMessage() throws Exception {
        Platform.runLater(() -> AlertMessages.setMessage(AlertMessages.AlertMessagesType.NAME, ""));
        functions.sleep(1000);
        functions.clickOn("Tamam");
    }
    @Test
    public void isEqual() throws Exception {
        Platform.runLater(() -> AlertMessages.isEqual(AlertMessages.AlertMessagesType.NOT_EQUAL_PASSWORD, "1", "2"));
        functions.sleep(1000);
        functions.clickOn("Tamam");
    }
    @Test
    public void isRange() throws Exception {
        Platform.runLater(() -> AlertMessages.isRange(AlertMessages.AlertMessagesType.IDENTIFICATION_NUMBER, 1, 2,5));
        functions.sleep(1000);
        functions.clickOn("Tamam");
    }
    @BeforeClass
    public static void beforeClass() throws Exception{
        FxToolkit.registerPrimaryStage();
    }
    @AfterClass
    public static void afterClass() throws Exception{
        FxToolkit.hideStage();
    }
    @Override
    public void start(Stage stage) throws Exception {
    }
}

@RunWith(PowerMockRunner.class)
@PrepareForTest( {Database.class, AlertManager.class, ItineraryListController.class} )
public class ItineraryControllerTest extends TestFXGuiBase{

    FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/fxml/itineraryManagement/addItinerary.fxml"));

    @Override
    public void start(Stage stage) throws Exception {
        Parent root = fxmlLoader.load();
        Scene scene = new Scene(root);
        stage.setScene(scene);
        stage.show();
    }

    @Test
    public void addItinerarySuccessTestFunction() throws Exception{
     }
}

![untitled](https://user-images.githubusercontent.com/18441333/34974329-6ec5937a-fa9d-11e7-9630-cda46ec56ef4.jpg)

**Comment by brcolow** [comment]
This error could be caused by a number of things. It looks like you are launching your application more than once, but I am not sure because I have never encountered a "Native library ___ already loaded in another classloader" error before.

**Comment by BurcuKalkan** [comment]
I found the reason @RunWith(PowerMockRunner.class). when I remove it dll exception is removed but this time no last call on a mock available exception thrown. But I don't found the solution yet. TestFx and powermockito using gives this exception

**Comment by brcolow** [comment]
I don't think this is a TestFX issue. Sorry I can't be of more assistance.
