### ISSUE TITLE
JFoenix TreeTableView

### ISSUE THREAD

**Issue by Timunas** [TestFX/TestFX#533]
Hi,

I'm using JFoenix Tree Table view and I want to validate how many rows that table has and what is the row content.

I was trying to validate the number of rows using

`verifyThat("#raceTable", TableViewMatchers.hasNumRows(1));`

But I get this:

`java.lang.AssertionError: 
Expected: TableView has 1 rows
     but: was a com.jfoenix.controls.JFXTreeTableView (<JFXTreeTableView[id=raceTable, styleClass=tree-table-view]>)
Expected :TableView has 1 rows
     
Actual   :a com.jfoenix.controls.JFXTreeTableView (<JFXTreeTableView[id=raceTable, styleClass=tree-table-view]>)
 <Click to see difference>

	at org.testfx.api.FxAssert.verifyThatImpl(FxAssert.java:185)
	at org.testfx.api.FxAssert.verifyThat(FxAssert.java:80)`

Is that anyway to work with this treetableview?

**Comment by Timunas** [comment]
Do you plan to add it in the next release?

**Comment by brcolow** [comment]
It should be relatively simple by using `TableViewMatchers` as a reference. Is it something you would be willing to take a stab at? Otherwise I will try and do it within a reasonable time-frame, can't make any guarantees about when, though.

**Comment by Timunas** [comment]
I could try to see that.
