### ISSUE TITLE
lateinit property xxx has not been initialized with TestFX in Kotlin

### ISSUE THREAD

**Issue by Gabirel** [TestFX/TestFX#562]
## Expected Behavior
I want to test `Controller` class with TestFX, but it didn't work.

And I'm using Kotlin. I've already submitted a question on StackOverflow. 
Here's the link: https://stackoverflow.com/questions/49919540/lateinit-property-xxx-has-not-been-initialized-with-testfx-in-kotlin

But still, I can't make it right.
[this](https://stackoverflow.com/a/49923196/8587335) don't think my approach (with using @FXML in the test class itself) can work at all. So my question is how could I make it work for me?

## Actual Behavior
Here are my codes:

`MainTest.java`:

```java

    package com.sample;

    +import xx;

    public class MainTest extends Application {

        @Override
        public void start(Stage primaryStage) throws Exception{
            Parent root = FXMLLoader.load(getClass().getResource("mainwindow.fxml"));
            primaryStage.setTitle("Test");
            primaryStage.setScene(new Scene(root, 909, 621));
            primaryStage.show();
            primaryStage.toFront();
        }

        @Before
        public void setUp() throws Exception {
        }

        @After
        public void tearDown() throws Exception {
        }
    }
```

`ControllerTest.kt`:

```kotlin

    package com.sample
    
    +import xx
    
    
    class ControllerKTest {
    	@FXML
    	private lateinit var root: AnchorPane
    
    	private lateinit var snackBar: JFXSnackbar
    
    	@FXML
    	fun initialize() {
    		snackBarInitialize()
    	}
    
    	private fun snackBarInitialize() {
    		snackBar = JFXSnackbar(root)
    		snackBar.styleClass.add("jfx-snackbar-action")
    		snackBar.stylesheets.add("css/jfoenix-components.css")
    	}
    
    	@Before
    	fun setUp() {
    		FxToolkit.registerPrimaryStage()
    		FxToolkit.setupApplication(MainTest::class.java)
    		initialize()
    	}
    
    	private var count = 0
    
    
    	@Test
    	fun onStartButtonMouseClicked() {
    		if (count++ % 2 == 0) {
    			snackBar.fireEvent(JFXSnackbar.SnackbarEvent("Toast Message $count"))
    		} else {
    			if (count % 4 == 0) {
    				snackBar.fireEvent(JFXSnackbar.SnackbarEvent(
    					"Snackbar Message Persistant $count",
    					"CLOSE",
    					3000,
    					true
    				) { b -> snackBar.close() })
    			} else {
    				snackBar.fireEvent(JFXSnackbar.SnackbarEvent(
    					"Snackbar Message $count",
    					"UNDO",
    					3000,
    					false
    				) { b -> })
    			}
    		}
    	}
    
    	@After
    	fun tearDown() {
    		FxToolkit.cleanupStages()
    	}
    }
```

However, it gives me this:
```java
    kotlin.UninitializedPropertyAccessException: lateinit property root has not been initialized

	at com.sample.ControllerKTest.snackBarInitialize(ControllerKTest.kt:55)
	at com.sample.ControllerKTest.initialize(ControllerKTest.kt:51)
	at com.sample.ControllerKTest.setUp(ControllerKTest.kt:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

----
PS: 
-  `lateinit property snackBar has not been initialized` will be reported if I **remove** `initialize()` from `setUp()`
- `lateinit property root has not been initialized` will be reported if I **add** `initialize()` from `setUp()`

## Specifications

  - Version: 4.0.13-alpha
  - Platform: Linux

**Comment by brcolow** [comment]
I don't know what `lateinit` means in Kotlin. I don't know anything about Kotlin. If you can show me the equivalent Java code I can definitely help you debug it but as it is I will have a hard time helping you.

**Comment by Gabirel** [comment]
Kotlin's code is almost identical to Java's code. But in some ways, it has subtle difference. I hope it will be the same.

Here's the Java code: (Have the same issue)

`MainTest.java`: 

```java
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class MainTest extends Application {


    @Override
    public void start(Stage primaryStage) throws Exception{
        Parent root = FXMLLoader.load(getClass().getResource("sample.fxml"));
        primaryStage.setTitle("Test: With TestFX");
        primaryStage.setScene(new Scene(root, 909, 621));
        primaryStage.show();
        primaryStage.toFront();
    }

    @Before
    public void setUp() throws Exception {
    }

    @After
    public void tearDown() throws Exception {
    }

    @Test
    public void main() {
    }

    @Test
    public void start1() {
    }

    @Test
    public void main1() {
    }
}
```

----
`ControllerTest.java`:

```java
import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXSnackbar;
import com.jfoenix.controls.JFXTextArea;
import javafx.fxml.FXML;
import javafx.scene.layout.AnchorPane;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.testfx.api.FxToolkit;

public class ControllerTest {

    @FXML
    private JFXButton clickButton;

    @FXML
    private JFXTextArea textArea;

    @FXML
    private AnchorPane root;

    private JFXSnackbar snackBar;

    @Before
    public void setUp() throws Exception {
        FxToolkit.registerPrimaryStage();
        FxToolkit.setupApplication(MainTest.class);
    }


    @Test
    public void onClickButtonMouseClicked() {
        snackBar.fireEvent(new JFXSnackbar.SnackbarEvent("Message sent"));
    }


    @FXML
    private void initialize() {
        snackBarInitialize();
    }

    private void snackBarInitialize() {
        snackBar = new JFXSnackbar(root);
        snackBar.getStyleClass().add("jfx-snackbar-action");
        snackBar.getStylesheets().add("css/jfoenix-components.css");
    }

    @After
    public void tearDown() throws Exception {
        FxToolkit.cleanupStages();
    }
}
```

----

And I got `NPE`: 
```java
java.lang.NullPointerException
	at ControllerTest.onClickButtonMouseClicked(ControllerTest.java:34)
	at ControllerTest.testOnClickButton(ControllerTest.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Please help me.

**Comment by brcolow** [comment]
Let's move it into one class for simplicity sake:

```java
import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXSnackbar;
import com.jfoenix.controls.JFXTextArea;
import javafx.fxml.FXML;
import javafx.scene.layout.AnchorPane;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.testfx.api.FxToolkit;

public class ControllerTest extends ApplicationTest {

    @FXML
    private JFXButton clickButton;

    @FXML
    private JFXTextArea textArea;

    @FXML
    private AnchorPane root;

    private JFXSnackbar snackBar;
    
    @Override
    public void start(Stage stage) {
        this.stage = stage;
    }

    @Before
    public void beforeEachTest() throws Exception {
        Platform.runLater(() -> {
            Parent root = FXMLLoader.load(getClass().getResource("sample.fxml"));
            stage.setTitle("Test: With TestFX");
            stage.setScene(new Scene(root, 909, 621));
            stage.show();
            stage.toFront();
            
            snackBar = new JFXSnackbar(root);
            // Does snackBar need to be added to the scene?
            snackBar.getStyleClass().add("jfx-snackbar-action");
            snackBar.getStylesheets().add("css/jfoenix-components.css");
        });
        WaitForAsyncUtils.waitForFxEvents();
    }
    
    @Test
    public void onClickButtonMouseClicked() {
        snackBar.fireEvent(new JFXSnackbar.SnackbarEvent("Message sent"));
    }
    
    @After
    public void tearDown() throws Exception {
        FxToolkit.cleanupStages();
    }
}
```
As noted in my comment, does snackbar need to be added to the Scene? I am not sure what it is or how it works, so I am not sure.

**Comment by Gabirel** [comment]
- Yes, `snackBar` has to be added to a `pane`. That's how `JFeonix` works. And that's why I have to deal with it.
- I made some changes to your code. here's the newest code: 

```java
import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXSnackbar;
import com.jfoenix.controls.JFXTextArea;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.testfx.api.FxToolkit;
import org.testfx.framework.junit.ApplicationTest;
import org.testfx.util.WaitForAsyncUtils;

public class ControllerTest extends ApplicationTest {

    @FXML
    private JFXButton clickButton;

    @FXML
    private JFXTextArea textArea;

    @FXML
    private AnchorPane root;

    private JFXSnackbar snackBar;
    private Stage stage;

    @Override
    public void start(Stage stage) {
        this.stage = stage;
    }

    @Before
    public void beforeEachTest() {
        Platform.runLater(() -> {
            try {

            Parent root = FXMLLoader.load(getClass().getResource("sample.fxml"));
            stage.setTitle("Test: With TestFX");
            stage.setScene(new Scene(root, 909, 621));
            stage.show();
            stage.toFront();

            // I got NPE here. Because JFSnackbar needs a pane to initialize. If that pane, which is `this.root`, is not initialized, it will report NPE
            snackBar = new JFXSnackbar(this.root);
            // Does snackBar need to be added to the scene?
            // Yes, It has to be
            snackBar.getStyleClass().add("jfx-snackbar-action");
            snackBar.getStylesheets().add("css/jfoenix-components.css");
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
        WaitForAsyncUtils.waitForFxEvents();
    }

    @Test
    public void onClickButtonMouseClicked() {
        snackBar.fireEvent(new JFXSnackbar.SnackbarEvent("Message sent"));
    }

    @After
    public void tearDown() throws Exception {
        FxToolkit.cleanupStages();
    }
}
```
----
`NPE`: 
```java
--- Exception in Async Thread ---
java.lang.NullPointerException: null
	com.jfoenix.controls.JFXSnackbar.refreshPopup(JFXSnackbar.java:331)
	com.jfoenix.controls.JFXSnackbar.lambda$new$2(JFXSnackbar.java:120)
        ..........
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by Gabirel** [comment]
Can you be more specific? I still don't understand.

My `sample.fxml` has `fx:controller="ControllerTest"`. So, I don't think I need to `setController` inside the `beforeEachTest`.

If I were wrong, I would do like this:

`MainTest.java`: 
```java
import javafx.application.Platform;
+......
import org.testfx.util.WaitForAsyncUtils;

public class MainTest extends ApplicationTest {
    private Stage stage;

    @Override
    public void start(Stage stage) {
        this.stage = stage;
    }

    @Before
    public void beforeEachTest() {
        Platform.runLater(() -> {
            try {
                FXMLLoader loader = FXMLLoader.load(getClass().getResource("sample.fxml"));
                // Is this really necessary even if I have `fx:controller="ControllerTest"`?
                loader.setController(ControllerTest.class);
                Parent root = loader.load();
                stage.setTitle("Test: With TestFX");
                stage.setScene(new Scene(root, 909, 621));
                stage.show();
                stage.toFront();

            } catch (Exception e) {
                e.printStackTrace();
            }
        });
        WaitForAsyncUtils.waitForFxEvents();
    }

    @After
    public void tearDown() throws Exception {
        FxToolkit.cleanupStages();
    }
}
```

`ControllerTest.java`: 
```java
import com.jfoenix.controls.JFXButton;
+......
import org.testfx.framework.junit.ApplicationTest;

public class ControllerTest extends ApplicationTest {

    @FXML
    private JFXButton clickButton;

    @FXML
    private JFXTextArea textArea;

    @FXML
    private AnchorPane root;

    private JFXSnackbar snackBar;


    @FXML
    public void onClickButtonMouseClicked() {
        snackBar.fireEvent(new JFXSnackbar.SnackbarEvent("Message sent"));
        sleep(2000);
    }
}
```

---
Then the question is where should I add `@Test` and how can I start testing?

Do I miss something or misunderstand something?
