### ISSUE TITLE
Issue with NodeQuery, Intelli J chooses the wrong class

### ISSUE THREAD

**Issue by Demytruk** [TestFX/TestFX#592]
Hey there! 

I'm trying to tested GIU of JavaFX/Spring app, but for two days i'm stuck.

Test file:
` import javafx.scene.control.Menu;
import javafx.scene.control.MenuItem;
import javafx.application.Platform;
import org.junit.After;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.testfx.assertions.api.Assertions.*;

import javax.annotation.PostConstruct;
@Test
    public void menuHelpItemsContainProperText() {
        assertThat(lookup("#menuHelp").queryAs(Menu.class)).hasText("Help");
        assertThat(lookup("#menuHelpContents").queryAs(MenuItem.class)).hasText("Contents");
        assertThat(lookup("#menuHelpAbout").queryAs(MenuItem.class)).hasText("About");
    }`

FXML File:
`  <Menu fx:id="menuHelp" mnemonicParsing="false" text="%MENU_HELP">
            <items>
              <MenuItem fx:id="menuHelpContents" mnemonicParsing="false" text="%MENU_CONTENTS" />
                  <MenuItem fx:id="menuHelpAbout" mnemonicParsing="false" text="%MENU_ABOUT" />`

Error pops out:
 java: method queryAs in interface org.testfx.service.query.NodeQuery cannot be applied to given types;
  required: java.lang.Class<T>
  found: java.lang.Class<javafx.scene.control.MenuItem>
  reason: inference variable T has incompatible bounds
    equality constraints: javafx.scene.control.MenuItem
    upper bounds: javafx.scene.Node

I'm fighting with that the second day, what I'm doing wrong?

**Comment by brcolow** [comment]
MenuItem assertJ assertions have not been added yet.

See https://github.com/TestFX/TestFX/pull/584#issuecomment-399269603 for a description of what is needed.

**Comment by Demytruk** [comment]
Thank you for the hint.
I was advised to get around the problem differently. I substitute MenuItem as MenuBar class in loop
`  @Test
    public void menuBarShouldContainProperText_menuHelp_AddToOverView() {
        MenuBar bar = lookup("#menuBar").queryAs(MenuBar.class);
        for (Menu menu : bar.getMenus()) {
            if (menu.getId().equals("#menuHelp")) {
                for (MenuItem item : menu.getItems()) {
                    if (item.getId().equals("#menuHelpContents")) {
                        Assertions.assertThat(item).isEqualTo
                                (mainView.getResourceBundle().get().getString("MENU_CONTENTS"));
                    }
                }
            }
        }
    }`

Now I have a problem with java.nio.BufferOverflowException
`java.nio.BufferOverflowException
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:363)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
java.nio.BufferOverflowException
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:363)
	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)`
