### ISSUE TITLE
OpenJFX 11 compatibility issue

### ISSUE THREAD

**Issue by o0oGnas** [TestFX/TestFX#638]
When I try to run tests with OpenJFX 11 I get the following error:
java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in unnamed module @0xb9b00e0) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to unnamed module @0xb9b00e0
	org.testfx.toolkit.impl.ToolkitServiceImpl.registerApplicationParameters(ToolkitServiceImpl.java:142)
	org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupApplication$6(ToolkitServiceImpl.java:125)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	java.base/java.lang.Thread.run(Thread.java:834)

**Comment by brcolow** [comment]
This is a normal jigsaw error that can be corrected by adding the following run-time arguments to `java`:

`--add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED`

**Comment by claudio-rosati** [comment]
I have the same problem when `FxToolkit.cleanupStages()` is called:

```
--- Exception in Async Thread ---
java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in unnamed module @0x518cdc84) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to unnamed module @0x518cdc84
	org.testfx.toolkit.impl.ToolkitServiceImpl.registerApplicationParameters(ToolkitServiceImpl.java:142)
	org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupApplication$6(ToolkitServiceImpl.java:125)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	java.base/java.lang.Thread.run(Thread.java:834)
--- Trace of caller of unhandled exception in Async Thread ---
	java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
	org.testfx.util.WaitForAsyncUtils$ASyncFXCallable.<init>(WaitForAsyncUtils.java:650)
	org.testfx.util.WaitForAsyncUtils.async(WaitForAsyncUtils.java:193)
	org.testfx.toolkit.impl.ToolkitServiceImpl.setupApplication(ToolkitServiceImpl.java:123)
	org.testfx.api.FxToolkit.setupApplication(FxToolkit.java:153)
	org.testfx.framework.junit.ApplicationTest.internalBefore(ApplicationTest.java:86)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:566)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by claudio-rosati** [comment]
It is something I’m trying to understand how to do with Maven: I’ve tried to add it as arg parameter inside the surfire plugin configuration without success. Tomorrow I’ll investigate more, hopefully finding some examples somewhere in the web.

**Comment by brcolow** [comment]
If `ALL-UNAMED` works but your module id doesn't, that means that Maven is not producing a fully modularized project for you. There is probably some missing Jigsaw related config somewhere in your `pom.xml`. Try and see if there is any missing config from some of the great blog posts about the transition to Jigsaw (Java 9) with Maven. Anyways, I am glad it is working for you now. I would like to make it so that argument isn't necessary but I don't think there is anyway to get around it:

https://github.com/TestFX/TestFX/blob/9d3d1297798cfd1b264b98d290d56f0430d2294f/subprojects/testfx-core/src/main/java/org/testfx/toolkit/impl/ToolkitServiceImpl.java#L141

**Comment by claudio-rosati** [comment]
Instead of `ALL-UNNAMED` I should put `org.testfx` because this is the module needing the access. But in my `module-info` I don't require it because it's only used for tests (and inside the POM file the dependencies to `org.testfx` have `test` scope).

It works only if

- `requires org.testfx;` is added to my `module-info- class, and
- `testfx-core` has a `compile` scope in pom dependencies.

But hit is something I don't want. The real Java 9/10/11 problem seems not being able to "enrich" the `module-info` class with more info coming from the test source base.

**Comment by brcolow** [comment]
Good point on the `ALL-UNAMED` vs `org.testfx`. I would suggest googling something like "maven jigsaw test dependencies" to see what the current state of things are. Looks like there is some information here:

https://stackoverflow.com/questions/47146491/java9-multi-module-maven-project-test-dependencies?noredirect=1&lq=1
https://stackoverflow.com/questions/52110023/how-do-you-organize-tests-in-a-modular-java-project?noredirect=1&lq=1

There should definitely be a way to keep TestFX as a `test` scoped dependency only with Maven + Jigsaw.

**Comment by patilnikhilh80** [comment]
Hi does anybody got the working solution?
my error
java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in module org.testfx) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to module org.testfx

**Comment by EachOneChew** [comment]
@brcolow Hi there, may I ask how to approach this when working with Kotlin + Gradle? I have tried putting the option in the jvm arguments of tests, as well as before all java compile / test tasks. Unfortunately, I either get `Unrecognized option: --add-exports` or the same error as OP.

**Comment by cachandlerdev** [comment]
Has this issue with TestFX ever been resolved? I tried to fix it by exporting `com.sun.javafx.application` to `org.testfx` in my build.gradle file, but this did not seem to work.

build.gradle:
```
run {
    jvmArgs = [
            '--add-exports=javafx.graphics/com.sun.javafx.application=org.testfx',
    ]
}
```

Error:
`java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in module org.testfx) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to module org.testfx
`

**Comment by EachOneChew** [comment]
> Has this issue with TestFX ever been resolved? I tried to fix it by exporting `com.sun.javafx.application` to `org.testfx` in my build.gradle file, but this did not seem to work.
> 
> build.gradle:
> 
> ```
> run {
>     jvmArgs = [
>             '--add-exports=javafx.graphics/com.sun.javafx.application=org.testfx',
>     ]
> }
> ```
> 
> Error: `java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in module org.testfx) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to module org.testfx `

Sorry, I don't quite remember how, but I pulled some jank that got TestFX working for me. Here's the repo where I did it though:

https://github.com/EachOneChew/JANTA/tree/master/NoteApp

**Comment by cachandlerdev** [comment]
For anyone else that finds this post, the only real solution I found to this problem was to use a non modular project (by deleting `module-info.java` ).

**Comment by AlirezaAsgarian** [comment]
I use intellij IDE and i don't know how i have to 
Did you try add "--add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED" to the runtime java arguments in intellij 
i searched but i didn't understand what i should do

**Comment by Snorri1986** [comment]
@claudio-rosati Thanks.
For fine for me

**Comment by mvsoder** [comment]
This should also be "fixed" in the upcoming 4.0.17 release.

**Comment by BasVerdoorn** [comment]
With my school groups project your solutions didn't work for me. The testfunctions work without any problem but still cause errors in the background. Our project doesn't have a module.info file. 

I think that's its possible because i startup the application via the OVAppUI class witch extents application instead of ApplicationTest. I could implement a sepprate startup via een ApplicationTest class but i don't know how i could implement that all other classes would use the switchToScene function of the test class during testing. I also prefer not to have to implement the same code in multiple places.

**my errors**
``` console
java.lang.IllegalAccessException: class org.testfx.toolkit.impl.ToolkitServiceImpl cannot access class 
com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not
export com.sun.javafx.application to unnamed module @14bf9759
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
FutureTask.java:317
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
ThreadPoolExecutor.java:1144
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
ThreadPoolExecutor.java:642
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

``` console
java.lang.reflect.InaccessibleObjectException: Unable to make field private static java.util.Map 
com.sun.javafx.application.ParametersImpl.params accessible: module javafx.graphics does not 
"opens com.sun.javafx.application" to unnamed module @14bf9759
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:94)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:52)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:70)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:100)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:520)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:748)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:443)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:211)
```

My test class code:
``` java
package com.mobiliteitsfabriek.ovapp.service;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;
import org.testfx.framework.junit5.ApplicationTest;

import com.mobiliteitsfabriek.ovapp.config.GlobalConfig;
import com.mobiliteitsfabriek.ovapp.ui.OVAppUI;

import javafx.stage.Stage;

public class LoginUITest extends ApplicationTest {

    @Override
    public void start(Stage stage) throws Exception {
        OVAppUI ovAppUI = new OVAppUI();
        ovAppUI.start(stage);
    }

    @Test
    void testValidLogin() {
        ServiceTest.executeUserWorkflow(() -> {
            // Ga naar de login pagina
            clickOn("#loginButton");

            // Voer een geldige gebruikersnaam en wachtwoord in
            clickOn("#usernameField").write(GlobalConfig.TEST_USERNAME);
            clickOn("#passwordField").write(GlobalConfig.TEST_PASSWORD);

            // Klik op de login-knop
            clickOn("#submitButton");

            // Controleer of de Home-pagina is geladen
            assertTrue(lookup("#homePageMainContainer").tryQuery().isPresent(), "Home page should be loaded after a successful login.");
        });
    }

    @Test
    void testInvalidPassword() {
        // Ga naar de login pagina
        clickOn("#loginButton");

        // Voer een geldige gebruikersnaam en een ongeldig wachtwoord in
        clickOn("#usernameField").write(GlobalConfig.TEST_USERNAME);
        clickOn("#passwordField").write("WrongPassword");

        // Klik op de login-knop
        clickOn("#submitButton");

        // Controleer of een foutmelding wordt weergegeven
        assertTrue(lookup(".invalid-input-label").tryQuery().isPresent(), "An error message should be displayed for invalid login.");
    }

    @Test
    void testEmptyFields() {
        // Ga naar de login pagina
        clickOn("#loginButton");

        // Laat beide velden leeg en klik op de login-knop
        clickOn("#submitButton");

        // Controleer of foutmeldingen voor beide velden worden weergegeven
        assertTrue(lookup(".invalid-input-label").tryQuery().isPresent(), "Error messages should be displayed for empty fields.");
    }
}
``` 
My JavaFX app startup en routing class. 
``` java
package com.mobiliteitsfabriek.ovapp.ui;

import com.mobiliteitsfabriek.ovapp.config.GlobalConfig;
import com.mobiliteitsfabriek.ovapp.service.SeedingService;
import com.mobiliteitsfabriek.ovapp.translation.TranslationHelper;
import com.mobiliteitsfabriek.ovapp.ui.pages.HomePage;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class OVAppUI extends Application {

    private static Stage stage;

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        final Scene scene = HomePage.getScene();

        primaryStage.setTitle(TranslationHelper.get("app.window.title"));
        primaryStage.setScene(scene);
        primaryStage.show();

        SeedingService service = new SeedingService();
        service.getAllStations();
    }

    public static void switchToScene(Scene scene) {
        // FIXME: setIconified true and then false is the only way i got the screenreader to start reading again
        //       after scene switch, if you find a better way please fix. 
        if (GlobalConfig.isUsingScreenreader) {
            stage.setIconified(true);
        }
        stage.setScene(scene);
        if (GlobalConfig.isUsingScreenreader) {
            stage.setIconified(false);
        }
    }
}
```
Parts of our pom.xml file. 
``` xml
<modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/>
        <!-- lookup parent from repository -->
    </parent>
<properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <!-- START JavaFX packages -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>23.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>23.0.1</version>
        </dependency>
        <!-- END JavaFX packages -->

        <!-- START JUnit 5 for unit testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <!-- END JUnit 5 for unit testing -->

        <!-- START TestFX for interface tests -->
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit5</artifactId>
            <version>4.0.18</version>
            <scope>test</scope>
        </dependency>
        <!-- END TestFX for interface tests -->
    </dependencies>
```

**My attempts with found solutions (didn't work):**
``` xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.1.2</version>
    <configuration>
        <argLine>
            --add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
        </argLine>
    </configuration>
</plugin>
 ```

``` xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.22.1</version>
  <configuration>
    <argLine>
      --add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
    </argLine>
  </configuration>
</plugin>
 ```
 
 ``` xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.2</version>
    <configuration>
        <argLine>
            --add-opens javafx.graphics/com.sun.javafx.application=org.testfx
            --add-opens javafx.graphics/com.sun.javafx.tk=org.testfx
        </argLine>
    </configuration>
</plugin>
 ```

 ``` xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.2</version>
    <configuration>
        <argLine>
            --add-opens javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
            --add-opens javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED
        </argLine>
    </configuration>
</plugin>
 ```

**Comment by cloudpaul** [comment]
We have the same error with TestFX 4.0.18, Java 17.0.2, JavaFX 17.0.2.
We don't use the module system, and aren't going to.
An update on this would be appreciated!

**Comment by JalenEvans** [comment]
Found a solution. I put this into my `build.gradle.kts` and it ran with no errors.
```kotlin
tasks.withType<Test> {
    useJUnitPlatform()
    jvmArgs(
        "--add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED"
    )
}
```
