### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by lanespade** [TestFX/TestFX#64]
Test FX works with JDK / JRE 8, but it fails with any version of 7. The error message is...

java.lang.RuntimeException: Unable to show stage
    at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:116)
    at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:100)
    at org.loadui.testfx.GuiTest.setupStage(GuiTest.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:77)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
    at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
    at org.loadui.testfx.GuiTest.showNodeInStage(GuiTest.java:111)
    ... 28 more

**Comment by JordanMartinez** [comment]
> In the future we will use Gradle to build the Jars. There will be a Configuration object, in which one could change the timeout duration.

Just curious, but was this ever done? I'm not sure if this issue needs to be open anymore.

**Comment by hastebrot** [comment]
Hi @JordanMartinez,

`FxToolkitContext` provides static `setLaunchTimeoutInMillis()` and `setSetupTimeoutInMillis()`.
 
https://github.com/TestFX/TestFX/blob/3e8d5cd06c9db75e77c61af4ca52034002ed5ea5/subprojects/testfx-core/src/main/java/org/testfx/api/FxToolkitContext.java#L112-L126

**Comment by JordanMartinez** [comment]
Then it seems that this issue can be resolved. And that's my point. The Issues tab has 4 pages of unresolved issues. How many of those issues have been resolved?
