### ISSUE TITLE
TableViewMatchers.hasTableCell fails when rows are populated in the test

### ISSUE THREAD

**Issue by torakiki** [TestFX/TestFX#643]
Hi, I had some hard time migrating my tests to the latest version. Tests for my tables were failing so, after some investigation I managed to create a unit to reproduce the issue. This is pretty much take from your unit tests, the difference is that the table is populated in the test method and not in the `start`, that's what I was doing in my tests.

## Expected Behavior
Test to succeed

## Actual Behavior
```
java.lang.AssertionError: 
Expected: TableView has table cell "alice"
     but: was [[alice, 30], [bob, 31], [carol, null], [dave, null]]
	at org.testfx.api.FxAssert.verifyThatImpl(FxAssert.java:162)
	at org.testfx.api.FxAssert.verifyThat(FxAssert.java:51)
```

Here the unit test https://gist.github.com/torakiki/6b1e3d5a6090bca33c6720e81b367765

## Specifications

  - Version: 4.0.15-alpha
  - Platform: 
Linux
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
JavaFX 11.0.1

**Comment by torakiki** [comment]
Yes, I already tried that and it fixed most of the unit tests that were failing. I still have 2 or 3 failing, I'll try to look into them. Just a note, after migrating all my tests to the latest version, the only failing tests I had are related to `TableView` and `TableViewMatchers` so maybe there's room for improvements there.
Thanks for the reply.
