### ISSUE TITLE
TestFX tests fail on Jenkins

### ISSUE THREAD

**Issue by elyday** [TestFX/TestFX#655]
I have written a test that should select something in a ChoiceBox and then it should be validated. This test does not work on the desktop computer when Jenkins runs the test.

Here is the test code:
```
ChoiceBox<Model> choiceBox = this.lookup("#choiceBox").query();
this.clickOn(choiceBox).type(KeyCode.DOWN).type(KeyCode.DOWN).type(KeyCode.ENTER);
verifyThat(choiceBox, node -> this.Model.get(2).equals(node.getValue()));
```

And this is the console output in Jenkins:
```
java.lang.AssertionError: 

Expected: applies on Predicate
     but: was <SomeChoiceBox[id=choiceBox, styleClass=choice-box]>
	at org.application.Test.lambda$testSimpleSteps$8(Test.java:160)
	at org.application.Test.step(Test.java:195)
	at org.application.Test.testSimpleSteps(Test.java:149)
```

`SomeChoiceBox` is an own implementation of the original ChoiceBox.
`public class SomeChoiceBox<T> extends ChoiceBox<T>`

I use TestFX in Version `4.0.8-alpha`

**Comment by elyday** [comment]
I updated on `4.0.14-alpha` and now it works
