### ISSUE TITLE
TravisCI & GitHub Actions - MediaException: Could not create player!

### ISSUE THREAD

**Issue by Tohaker** [TestFX/TestFX#693]
## Expected Behavior

Tests should pass as they do on a developer machine.

## Actual Behavior

The results from [this PR](https://github.com/GazePlay/GazePlay/pull/990) show the behaviour. Specifically the test file at `gazeplay/src/test/java/net/gazeplay/ui/MusicControlTest.java`

I'm using the same setup that works with our other JavaFX tests, but it appears that creating a MediaPlayer on a headless system doesn't work.

```
net.gazeplay.commons.utils.games.BackgroundMusicManagerTest > shouldHaveTheSameVolumeAsVolumeProperty() STANDARD_OUT
    2020-01-04 23:27:57,020 INFO  net.gazeplay.commons.utils.games.BackgroundMusicManager - audio folder : /home/runner/work/GazePlay/GazePlay/gazeplay-commons/src/test/resources/data/music/
    2020-01-04 23:27:57,030 ERROR net.gazeplay.commons.utils.games.BackgroundMusicManager - error while loading media file:/home/runner/work/GazePlay/GazePlay/gazeplay-commons/src/test/resources/data/music/song.mp3, type : UNKNOWN
    javafx.scene.media.MediaException: com.sun.media.jfxmedia.MediaException: Could not create player!
    	at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
    	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:518)
    	at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:421)
    	at net.gazeplay.commons.utils.games.BackgroundMusicManager.createMediaPlayer(BackgroundMusicManager.java:411)
```

Perhaps I'm missing some configuration, but this all works fine on a development machine (which isn't headless).

## Specifications

  - Version: 4.0.16 Alpha
  - Platform: Travis CI (Ubuntu 18.04) and GitHub Actions (`ubuntu-latest`) with OpenJDK 11

**Comment by brcolow** [comment]
I believe that it is a limitation of headless (Monocle) that it cannot create a MediaPlayer.
