### ISSUE TITLE
Add assertion for checking that no element is selected in ComboBox

### ISSUE THREAD

**Issue by marcin-chwedczuk** [TestFX/TestFX#728]
## Expected Behavior

There should be a method in `AbstractComboBoxAssert` like `doesNotHaveSelectedValue()` or even better `noValueIsSelected()`.

## Actual Behavior

Running test code:
```java
// control() is robot.lookup(idSelector()).queryComboBox();

        assertThat(control()) 
                .hasSelectedItem(null);
```

results in:
```
[ERROR] pl.marcinchwedczuk.javafx.validation.demo.topdown.TopDownIT.after_clicking_validate_fields_are_empty  Time elapsed: 0.322 s  <<< ERROR!
java.lang.NullPointerException
	at org.testfx.matcher.control.ComboBoxMatchers.hasSelectedItem(ComboBoxMatchers.java:122)
	at org.testfx.matcher.control.ComboBoxMatchers.lambda$hasSelectedItem$3(ComboBoxMatchers.java:69)
	at org.testfx.matcher.base.GeneralMatchers$3.matchesSafely(GeneralMatchers.java:120)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at org.testfx.assertions.impl.Adapter$1.matches(Adapter.java:45)
	at org.assertj.core.internal.Conditions.assertIs(Conditions.java:61)
```

To get the fastest possible support, create a [minimal example](https://stackoverflow.com/help/mcve)
and upload it to GitHub.

## Specifications

  - Version: Test FX 4.0.16-alpha

**Comment by eriknellessen** [comment]
+1, same problem here
