### ISSUE TITLE
Java 11 Headless Testing UnsupportedOperationException at GtkApplication

### ISSUE THREAD

**Issue by buracchi** [TestFX/TestFX#731]
## Expected Behavior

Should be able to run TestFX in Headless mode.

## Actual Behavior

TestFX in headless mode produces the following error:

```
TestClass > testName(FxRobot) FAILED
    java.lang.RuntimeException at WaitForAsyncUtils.java:301
        Caused by: java.lang.UnsupportedOperationException at GtkApplication.java:189
```

## Specifications

  - Version: OpenJDK 11
  - Platform: WSL (Ubuntu LTS) / ubuntu-latest on GitHub Actions
  - Gradle version: 7.0.2
  - JavaFx version: 11.0.2 / 16

My `build.gradle.kts` is the following:

```
plugins {
    id("com.ttbmp.cinehub.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.0.10"
}

dependencies {
    implementation(project(":app"))

    testImplementation("org.junit.jupiter", "junit-jupiter-api", "5.7.0")
    testRuntimeOnly("org.junit.jupiter", "junit-jupiter-engine")

    testImplementation("org.testfx", "testfx-core", "4.0.16-alpha")
    testImplementation("org.testfx", "testfx-junit5", "4.0.16-alpha")
    testImplementation("org.testfx", "openjfx-monocle", "jdk-11+26")
}

javafx {
    version = "16"
    modules("javafx.base", "javafx.controls", "javafx.fxml")
}

application {
    mainClass.set("com.ttbmp.cinehub.ui.desktop.CinehubApplication")
}

tasks.withType<Test>().all {
    if (project.hasProperty("headless")) {
        jvmArgs("-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw")
    }
}
```

Test classes can be summarized as:

```
@ExtendWith({ApplicationExtension.class})
class ExampleTest {

    @Start
    void onStart(Stage stage) {
        foo(stage);
        stage.show();
    }

    @Test
    void test(FxRobot robot) {
        FxAssert.verifyThat("#id", Node::isVisible);
    }

}
```

The test are launched with:

```
export DISPLAY=:99
sudo Xvfb -ac $DISPLAY -screen 0 1920x1080x32 > /dev/null 2>&1 &
./gradlew -Pheadless=true :ui:desktop:build
```

This is a stack trace of a failed test:

```
java.lang.RuntimeException: java.lang.UnsupportedOperationException: Internal Error
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:301)
	at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:107)
	at org.testfx.framework.junit5.ApplicationExtension.beforeEach(ApplicationExtension.java:84)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:159)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:195)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:195)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:158)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:125)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.util.concurrent.TimeoutException: FX Application Thread not running
		at org.testfx.api.FxToolkit.cleanupApplication(FxToolkit.java:169)
		at org.testfx.framework.junit5.ApplicationExtension.afterEach(ApplicationExtension.java:90)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:253)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:269)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:269)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:268)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:252)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
		... 68 more
Caused by: java.lang.UnsupportedOperationException: Internal Error
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:189)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:288)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	... 1 more
```

**Comment by nathanwonnacott** [comment]
@buracchi did you ever find a work around for this? This is a major blocker for my team in moving to Java 11

**Comment by buracchi** [comment]
@nathanwonnacott as far as I can remember, the only useful information I could find on this problem was an outdated post by Andres Almiray in which he suggested that the problem could be related to the freezing of the mouse pointer if I remember correctly, but his proposed workaround didn't fix the problem.
Unfortunately, due to our deadlines and the lack of official support my team ended up not implementing automated tests for javafx.
I would suggest to ssh into the server, export the DISPLAY to a different machine and actaully saw the test run to confirm whether the mouse freezing is the real problem.

**Comment by nathanwonnacott** [comment]
@buracchi bummer. Thanks for the info. I'll post whatever I figure out for anyone else interested in the future.

**Comment by nathanwonnacott** [comment]
Actually, I got this working. I may have not been running into the same problem, but for my issue I could resolve this just by installing libgtk (apt-get instally libgtk-3-0). Usually libgtk 3 is installed on Ubuntu by default, but since I was using a Ubuntu docker image made specifically for our CI/CD pipeline, it doesn't have all of the common GUI related packages installed.

@buracchi you mentioned that you were using WSL Ubuntu, which also does not include libgtk by default, so this could be your issue as well. If that's the case, then it is not a TestFX issue, but rather just a case where JavaFX should add a better error message.

**Comment by MarcPartensky** [comment]
Thanks for the tip it made all the difference for me !

**Comment by deliciouslytyped** [comment]
You guys just saved me a very long night of hopeless debugging. Thanks.
Error for trying to help other people google:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Internal Error                                     
        at javafx.graphics@20.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:223)                                                                                                                                   
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)                            
        at javafx.graphics@20.0.1/com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:200)                                                                                                                                         
        at javafx.graphics@20.0.1/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)                                                                                                                       
        at javafx.graphics@20.0.1/com.sun.glass.ui.Application.run(Application.java:146)                                                                                                                                                      
        at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)            
        at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)               
        at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)               
        at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)                                                                                                                                 
        at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)                                                                                                                           
        at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)                                                                                                                   
        at java.base/java.lang.Thread.run(Thread.java:833) 
```
