### ISSUE TITLE
Headless tests hang when using java 8u311

### ISSUE THREAD

**Issue by lama-akeila** [TestFX/TestFX#738]
I have tests for a javaFX application that used to work using java 8u101
Once upgrading to the latest version of java 8 ( 8u311 ) the tests execution hang.
The build gets executed successfully when running the tests in normal mode (gradle build). When I run in headless mode (gradle build -Pheadless=true) the execution hangs

I even tried to create one test class 
<code>
public class TestClassA extends ApplicationTest
{

  @Override
  public void start(Stage stage) throws Exception
  {
  }

@Test
public void test1()
{
}
}

</code>
And the execution hangs with this one empty test class. When I uncomment the annotation @Test, the build with headless tests works... Looks like the minute I introduce @Test to a class that extends Application test, the problem occurs and the test hangs.

Any Idea what is happening?

## Specifications

  - Version:
  - javafx 8.1.1
    testCompile 'org.testfx:testfx-core:4.0.+'
    testCompile 'org.testfx:openjfx-monocle:8u76-b04'
    testCompile 'junit:junit:4.13-beta-3'
    testCompile 'org.testfx:testfx-junit:4.0.+'

Java version: Java 8u311
gradle 3.1

**Comment by lama-akeila** [comment]
here is the issue from the log file...

<code>
02:57:30.757 [DEBUG] [TestEventLogger] nanosonics.trophon2.servicemanufacturing.ui.AboutTest > closeDialog STANDARD_ERROR
02:57:30.757 [DEBUG] [TestEventLogger]     java.lang.NoSuchMethodException: com.sun.glass.ui.Screen.<init>(long, int, int, int, int, int, int, int, int, int, int, int, float)
02:57:30.758 [DEBUG] [TestEventLogger]     	at java.lang.Class.getConstructor0(Class.java:3082)
02:57:30.758 [DEBUG] [TestEventLogger]     	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
02:57:30.758 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.MonocleApplication$2.run(MonocleApplication.java:230)
02:57:30.758 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.MonocleApplication$2.run(MonocleApplication.java:226)
02:57:30.758 [DEBUG] [TestEventLogger]     	at java.security.AccessController.doPrivileged(Native Method)
02:57:30.758 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.MonocleApplication.staticScreen_getScreens(MonocleApplication.java:225)
02:57:30.758 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.Screen.initScreens(Screen.java:412)
02:57:30.758 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.Application.lambda$run$1(Application.java:155)
02:57:30.759 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
02:57:30.759 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
02:57:30.759 [DEBUG] [TestEventLogger]     	at java.lang.Thread.run(Thread.java:748)
02:57:30.759 [DEBUG] [TestEventLogger]     --- Exception in Async Thread ---
02:57:30.759 [DEBUG] [TestEventLogger]     java.lang.NullPointerException: null
02:57:30.759 [DEBUG] [TestEventLogger]     	com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:729)
02:57:30.759 [DEBUG] [TestEventLogger]     	com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:334)
02:57:30.759 [DEBUG] [TestEventLogger]     	com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:279)
02:57:30.759 [DEBUG] [TestEventLogger]     	com.sun.glass.ui.Application.lambda$run$1(Application.java:156)
02:57:30.759 [DEBUG] [TestEventLogger]     	com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
02:57:30.759 [DEBUG] [TestEventLogger]     	com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
02:57:30.759 [DEBUG] [TestEventLogger]     	java.lang.Thread.run(Thread.java:748)
02:57:30.759 [DEBUG] [TestEventLogger] 
02:57:40.260 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
02:57:40.267 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:57:40.267 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
02:57:40.268 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:57:40.271 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:57:40.272 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
02:57:40.272 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:57:50.258 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
02:57:50.261 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:57:50.262 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.

</code>

**Comment by broecirr** [comment]
The versions of Monocle published aren't up to date. A fix is to build your own version for the version of Java you're using: follow the instructions under "Manual Update" [here](https://github.com/TestFX/Monocle).
