### ISSUE TITLE
Headless mode tests start failing with JavaFX 20 due to stage focus behavior change

### ISSUE THREAD

**Issue by tcfurrer** [TestFX/TestFX#749]
## Expected Behavior
In general, TestFX headless (i.e. Monocle) tests which passed on JavaFX 19 should keep passing on JavaFX 20.  Also, tests which pass in non-headless mode should generally also pass while in headless mode.

## Actual Behavior
Some existing tests began failing -- only when run headless -- on JavaFX 20 due to a change that release made to stage focus behavior. The change apparently introduces a new divergence between headless and non-headless behavior:

https://bugs.openjdk.org/browse/JDK-8296621

Although it does make sense to avoid stealing focus to a stage only because it swaps it's scene... I'm not so sure about the stage no longer grabbing focus immediately after first showing (unfortunately that JDK issue itself doesn't mention this detail, but it was at least discussed during the code review).  I suspect that it still grabs focus after showing in non-headless, but not in headless, based on the evidence I collected so far.

One of the tests I'm seeing fail only opens the primary stage.  Another one opens primary stage and then also a dialog stage.  In both cases, adding stage.requestFocus() immediately after the call to stage.setScene() (or immediately after the dialog shows) makes the issue go away.  Since the same tests pass in JavaFX 19, and the same tests in non-headless mode don't require the same workaround, it seems like this must be a bug either in TestFX or Monocle (I'm not sure which).

I'm only filing this issue against TestFX because I'm not sure yet that it's only a Monocle bug.

I'm sorry not to provide a minimal example here yet... I don't have time at the moment, but still wanted to alert the community of this issue.  If I do find the time soon, I will provide a link to a GitHub repo with a minimal example.

## Known Workaround
Call stage.requestFocus() immediately after stage.setScene().  For Dialogs, call stage.requestFocus() in a listener of showingProperty() (may or may not work equally well in onShown hook?).

## Specifications

  - Version:  TestFX 4.0.16-alpha + OpenJDK 17 + OpenJFX 20 + JUnit 5.9.0 + Gradle 7.5.1
  - Platform: Happens the same on both Windows and Linux.

**Comment by tcfurrer** [comment]
I'm not sure whether this issue is indirectly related to #548 and/or #293.

**Comment by tcfurrer** [comment]
If I can get a minimal reproducing repo set up, I will also file a bug against OpenJFX in Oracle's bug database, just in case the root cause is partially or entirely there.

**Comment by tcfurrer** [comment]
It is also interesting to note that the changeset for that JDK bug touched Quantum, but not Monocle. However, I'm not at all an expert on the implementation side of JavaFX... so... just sayin'...

**Comment by tsayao** [comment]
I have tried to start working on this, but could not build monocle following this:

https://wiki.openjdk.org/display/OpenJFX/Monocle

**Comment by tsayao** [comment]
Maybe openjdk/jfx#1066 fixes it?

**Comment by kevinrushforth** [comment]
The underlying JavaFX bug is fixed, although it would be good for someone to verify it with TestFX. See [JDK-8306121](https://bugs.openjdk.org/browse/JDK-8306121) / openjdk/jfx#1110

It will be available in a early access build of JavaFX 21 about a week from now.

**Comment by dsubelman** [comment]
I can verify it once the early build is published.

**Comment by kevinrushforth** [comment]
An early access build of JavaFX 21 with the fix is now available here:

https://jdk.java.net/javafx21/

**Comment by dsubelman** [comment]
Is it possible to publish JavaFX 21-ea+23 in Maven repository? It would be much simple for me to test it.

**Comment by kevinrushforth** [comment]
Gluon publishes JavaFX binaries on Maven Central. I don't know whether build 21-ea+23 is there yet. @johanvos or @tiainen would know.

**Comment by johanvos** [comment]
The latest in Maven central is currently 21-ea+21, but we'll start the release work for 21-ea+23 soon.
Do you require a linux build with the monocle classes included? For the linux builds, we don't have automated builds with monocle atm, as that build process urgently needs some attention (we do manual builds and send them to maven central occasionally).

**Comment by dsubelman** [comment]
I can test it in macos. Is that possible?

**Comment by tiainen** [comment]
`21-ea+23` has just been released to maven central.

**Comment by dsubelman** [comment]
I did tests using TestFX headless (Monocle) and they failed with the exception posted below. This is a different exception than the one introduced in JavaFx 20. As you can see at the end of the exception, the issue seems to be in ```com.sun.glass.ui.monocle.MonocleWindow``` and the method ```void _updateViewSize(long)```.

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:301)
	at org.testfx.api.FxToolkit.waitForSetup(FxToolkit.java:244)
	at org.testfx.api.FxToolkit.setupApplication(FxToolkit.java:153)
	at org.testfx.framework.junit5.ApplicationExtension.beforeEach(ApplicationExtension.java:85)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:202)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:165)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:132)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.testfx.util.WaitForAsyncUtils$ASyncFXCallable.get(WaitForAsyncUtils.java:696)
	at org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupApplication$6(ToolkitServiceImpl.java:127)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testfx.framework.junit5.ApplicationExtension$AnnotationBasedApplicationFixture.start(ApplicationExtension.java:158)
	at org.testfx.framework.junit5.ApplicationAdapter.start(ApplicationAdapter.java:37)
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$0(ApplicationServiceImpl.java:49)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.graphics@21-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@21-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	... 1 more
Caused by: java.lang.AbstractMethodError: Receiver class com.sun.glass.ui.monocle.MonocleWindow does not define or inherit an implementation of the resolved method 'abstract void _updateViewSize(long)' of abstract class com.sun.glass.ui.Window.
	at javafx.graphics@21-ea/com.sun.glass.ui.Window.setView(Window.java:377)
	at javafx.graphics@21-ea/com.sun.javafx.tk.quantum.WindowStage.lambda$setScene$0(WindowStage.java:271)
	at javafx.graphics@21-ea/com.sun.javafx.tk.quantum.QuantumToolkit.runWithRenderLock(QuantumToolkit.java:442)
	at javafx.graphics@21-ea/com.sun.javafx.tk.quantum.WindowStage.setScene(WindowStage.java:270)
	at javafx.graphics@21-ea/javafx.stage.Window$SceneModel.updatePeerScene(Window.java:889)
	at javafx.graphics@21-ea/javafx.stage.Window$SceneModel.invalidated(Window.java:858)
	at javafx.base@21-ea/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.base@21-ea/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.graphics@21-ea/javafx.stage.Window.setScene(Window.java:823)
	at javafx.graphics@21-ea/javafx.stage.Stage.setScene(Stage.java:270)
	... 15 more
```

**Comment by dsubelman** [comment]
I was looking at recent commits and I found that the abstract method ```_updateViewSize(long)``` in ```com.sun.glass.ui.Window``` was added in JavaFX 21: [Commit: 8299968: Second call to Stage.setScene() create sizing issue with uiScale > 1.0](https://github.com/openjdk/jfx/commit/4051f1611646400b59ee871fb40399b933361ba2).

Somehow this is generating a ```java.util.concurrent.ExecutionException``` in TestFX at ```org.testfx.util.WaitForAsyncUtils.waitFor()```.

**Comment by kevinrushforth** [comment]
You will need to recompile Monocle with the latest JavaFX 21-ea in order to use it (independent of the bug you are trying to verify).

**Comment by mvsoder** [comment]
@kevinrushforth I recommend we make a new issue to create a new build of Monocle for Java 21.

**Comment by dsubelman** [comment]
> @kevinrushforth I recommend we make a new issue to create a new build of Monocle for Java 21.

That would work for me.

**Comment by johanvos** [comment]
@mvsoder or @dsubelman Do you build Monocle as part of TestFX or do you need a new "monocle build" in maven central?

**Comment by johanvos** [comment]
There are monocle builds in https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/21-ea+24/ which I hope are ok?
We don't automatically build monocle for Linux x86 platforms, as those fail to build with the development toolchain used to create (almost) reproducible builds. Is that a showstopper for you?
Long-term (actually the sooner the better) I think it would be much better to have a dedicated headless Glass platform, instead of using Monocle. Do you have any thoughts on that?

**Comment by mvsoder** [comment]
Monocle is pure Java when built on it's own. It's actually not very hard to build Monocle. I just would to get it published under the TestFX Maven org since most of us already find Monocle there.

**Comment by mvsoder** [comment]
Monocle does not require those native resources. It only requires this code: https://github.com/openjdk/jfx/tree/master/modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle. You can also review the TestFX/Monocle project for how it is done: https://github.com/TestFX/Monocle. The README is a bit out of date, but the concepts remain the same. Also note that I already have builds going as soon as I can get some PRs approved: https://github.com/TestFX/Monocle/actions. I'm really looking forward to getting more Monocle builds posted.

**Comment by kevinrushforth** [comment]
> > Monocle is pure Java when built on it's own. It's actually not very hard to build. I just want to get it published under the TestFX Maven org since most of us already find Monocle there.
> 
> I think that would be better. I am hesitating to put it in the openjfx maven repo, ...

I also think this would be better.

**Comment by dsubelman** [comment]
Hi all! Any news about the monocle build in maven central?

**Comment by mvsoder** [comment]
Now that we have TestFX 4.0.17 released I will turn attention to the Monocle artifacts.

**Comment by dsubelman** [comment]
Great! Thanks!

**Comment by dsubelman** [comment]
Do you know if an updated monocle build is still in the plan?

**Comment by mvsoder** [comment]
Yes, new Monocle builds are still in the plans. Real life just getting in the way.

**Comment by torakiki** [comment]
Not sure if it helps but I created this https://github.com/torakiki/javafx-monocle and released it on maven central a couple of months ago

**Comment by dsubelman** [comment]
> Yes, new Monocle builds are still in the plans. Real life just getting in the way.

Thanks, let me know if I can help.

**Comment by dsubelman** [comment]
> Not sure if it helps but I created this https://github.com/torakiki/javafx-monocle and released it on maven central a couple of months ago

Thanks! I saw your post on Monocle's repo about this and tried it, but couldn't make it work with TestFx.

**Comment by dsubelman** [comment]
I successfully ran tests with the new releases: [TestFx](http://testfx.org/) **4.0.18** and [OpenJFX Monocle](https://github.com/TestFX/Monocle) **17.0.10**. All my previously failing tests are now passing without any issues.

**Comment by mvsoder** [comment]
@dsubelman Glad to hear your tests are back up and running. Thanks for hanging in there. 😃
