### ISSUE TITLE
ThreadDeath with Jenkins

### ISSUE THREAD

**Issue by aliebelt** [TestFX/TestFX#75]
[TestFX 3.1.2 / Win 64bit / Jenkins for Windows 1.555]

With the new version of TestFX we can't run our tests with Jenkins anymore.
The UserInputDetector is erroneously reporting a user-input:

``` java
java.lang.ThreadDeath
    at java.lang.Thread.stop(Thread.java:849)
    at org.loadui.testfx.utils.UserInputDetector.userInputDetected(UserInputDetector.java:58)
    at org.loadui.testfx.utils.UserInputDetector.assertPointsAreEqual(UserInputDetector.java:42)
    at org.loadui.testfx.utils.UserInputDetector.run(UserInputDetector.java:27)
    at java.lang.Thread.run(Thread.java:744)
```

The simplest solution may be to make the user-input-detection optional...

Best regard
Andreas

**Comment by Ciruman** [comment]
Hi all,

Since version 3.1.2, there is no any other release. As consequence the UserInputDetector is still in the stable version. I really like this project and I think that it makes sence and at the same time I saw there are new commits. But there is no 4.0 release(it is still in alpha release).

What is the road map? plans?

Thanks!

**Comment by hastebrot** [comment]
@Ciruman The plan is **23rd of December 2015 for TestFX 4.1.0-beta** and **Q1 2016 for TestFX 4.2.0** (final). I'll change it from 4.0.0 to 4.1.0 to make it easier to use version intervals (like `4.1.+`) with Maven or Gradle and to align it to semantic versioning.

**Before 4.1.0-beta** I'll introduce `BoundsQuery` and improve `PointQuery`. I have a local Git branch for this. It took some time to align these new query classes to mouse-based robot methods like `FxRobot#clickOn()` and assertion methods like `FxAssert.verifyThat()`, and I need at least a week to finish this API. After this I'll declare most the API in `org.testfx.api` as stable, so that you can rely on it for your tests.

**Before 4.2.0** It'll take some months to get through all uses-cases that worked in TestFX 3 and test them in TestFX 4, through the issues on GitHub that need SSCCE example code. I guess these things only need code examples, maybe feature addition to the core, but no integral changes to the core API.

**Comment by Ciruman** [comment]
Is there any list of the remaining tasks needed for the release? (testing, documentation, bug fixing, etc.)

**Comment by hastebrot** [comment]
For 4.1.0-beta:
- https://github.com/TestFX/TestFX/issues/167
- https://github.com/TestFX/TestFX/issues/206

**Comment by Ciruman** [comment]
I did could not do it. Thank you for your great work.

**Comment by brcolow** [comment]
Closing due to inactivity and because this is an issue about the legacy, unmaintained version of TestFX.
