### ISSUE TITLE
clickOn() is not thread safe

### ISSUE THREAD

**Issue by adamish** [TestFX/TestFX#813]
## Expected Behaviour

Use of clickOn() without causing JavaFX threading issues

## Actual Behaviour

clickOn() can cause bounds recomputation. clickOn() is most commonly used from the test main thread (as per examples in documentation. This means that bounds recomputation is done off the JavaFX thread which can cause exceptions such as

```
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at org.testfx.util.WaitForAsyncUtils.---- Delayed Exception: (See Trace Below) ----(WaitForAsyncUtils.java:0)
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:305)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1704)
```

The cause is that isNodeVisible() ultimately calls getBoundsInLocal(). That method uses lazy initialization so if called before bounds are set will compute them from the current calling thread. This can be demonstrated with the following stack trace captured in the debugger

```
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1492) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115) ~[javafx-graphics-19.0.2-win.jar:?]
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84) ~[javafx-graphics-19.0.2-win.jar:?]
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78) ~[javafx-graphics-19.0.2-win.jar:?]
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3355) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168) ~[javafx-graphics-19.0.2-win.jar:?]
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89) ~[javafx-graphics-19.0.2-win.jar:?]
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:117) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.Node.updateGeomBounds(Node.java:3825) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.Node.getGeomBounds(Node.java:3787) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.Node.getLocalBounds(Node.java:3735) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.Node$MiscProperties$3.computeBounds(Node.java:6825) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9840) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9810) ~[javafx-graphics-19.0.2-win.jar:?]
	at javafx.scene.Node.getBoundsInLocal(Node.java:3415) ~[javafx-graphics-19.0.2-win.jar:?]
	at org.testfx.util.NodeQueryUtils.isNodeWithinSceneBounds(NodeQueryUtils.java:236) ~[testfx-core-4.0.17.jar:4.0.17]
	at org.testfx.util.NodeQueryUtils.isNodeVisible(NodeQueryUtils.java:231) ~[testfx-core-4.0.17.jar:4.0.17]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.testfx.service.query.impl.NodeQueryImpl.match(NodeQueryImpl.java:112) ~[testfx-core-4.0.17.jar:4.0.17]
	at org.testfx.api.FxRobot.queryVisibleNode(FxRobot.java:951) ~[testfx-core-4.0.17.jar:4.0.17]
	at org.testfx.api.FxRobot.pointOfVisibleNode(FxRobot.java:922) ~[testfx-core-4.0.17.jar:4.0.17]
	at org.testfx.api.FxRobot.clickOn(FxRobot.java:630) ~[testfx-core-4.0.17.jar:4.0.17]
```

To get the fastest possible support, create a [minimal example](https://stackoverflow.com/help/mcve)
and upload it to GitHub.

This behaviour can be forced by creating a small test that calls clickOn whilst other JavaFX layout is occurring

```
public class ClickOnThreadingIssueTest extends ApplicationTest {

    private HBox parent;

    @Override
    public void start(Stage stage) throws Exception {
        super.start(stage);
        parent = new HBox(new Button("Foo"));
        stage.setScene(new Scene(parent));
        stage.show();
    }

    @Test
    void clickOnThreadingIssue() {
        for (int i = 0; i < 10; i++) {
            WaitForAsyncUtils.asyncFx(() -> {
                parent.getChildren().remove(0);
                parent.getChildren().add(new Button("Foo"));
            });
            clickOn("Foo");
        }
    }
}
```
## Specifications

  - Version: 4.0.17
  - Platform: Linux, RHEL 8u6

**Comment by tcfurrer** [comment]
My project is having this exact same issue currently. This bug definitely deserves some priority because it's basically making TestFX generally unreliable. Unfortunately I personally don't have the time to submit a PR. However if we discover a good workaround, I'll reply here again with details...

**Comment by tcfurrer** [comment]
Just in case it helps anyone googling find this...
We're seeing another stack trace which I believe is the same root cause.

`Cannot invoke "javafx.scene.Scene.getWidth()" because "scene" is null
java.lang.NullPointerException: Cannot invoke "javafx.scene.Scene.getWidth()" because "scene" is null
	at org.testfx.service.locator.impl.BoundsLocatorImpl.limitToVisibleBounds(BoundsLocatorImpl.java:77)
	at org.testfx.service.locator.impl.BoundsLocatorImpl.boundsInSceneFor(BoundsLocatorImpl.java:33)
	at org.testfx.service.locator.impl.BoundsLocatorImpl.boundsOnScreenFor(BoundsLocatorImpl.java:50)
	at org.testfx.service.locator.impl.PointLocatorImpl.lambda$point$0(PointLocatorImpl.java:52)
	at org.testfx.service.query.impl.CallableBoundsPointQuery.fetchCallableBounds(CallableBoundsPointQuery.java:49)
	at org.testfx.service.query.impl.CallableBoundsPointQuery.query(CallableBoundsPointQuery.java:40)
	at org.testfx.robot.impl.MoveRobotImpl.moveTo(MoveRobotImpl.java:78)
	at org.testfx.robot.impl.ClickRobotImpl.clickOn(ClickRobotImpl.java:54)
	at org.testfx.api.FxRobot.clickOn(FxRobot.java:582)
	at org.testfx.api.FxRobot.clickOn(FxRobot.java:615)
	at org.testfx.api.FxRobot.clickOn(FxRobot.java:59)
	at org.testfx.api.FxRobotInterface.clickOn(FxRobotInterface.java:597)`

**Comment by tcfurrer** [comment]
Since this is really a problem with Node queries, I believe it's not unique to clickOn()?  One possible workaround is to wrap any code that performs a Node query in waitForAsyncFx(), but that clutters the code and is too easy to forget to do.

**Comment by tcfurrer** [comment]
This might be a duplicate of #143?

**Comment by tcfurrer** [comment]
We believe we've successfully worked around this bug by **_overriding almost every method in FxRobot to call super inside a waitForAsyncFx()_**. It's a bit painful to override so many methods, but since each one only needs a single line of code in the body, this code could be automatically generated.

We've got this working via a class that extends ApplicationTest, but I assume the same could work by extending ApplicationExtension.

We are using JUnit5. I can't speak to whether/how this might work for other test frameworks.

**Comment by tcfurrer** [comment]
Our suite of only about 35 tests was extremely unstable prior to applying the workaround (it consistently took <2 minutes of test execution to hit this bug a handful of times). I believe that this bug should be the top priority for TestFX improvement in the short term, as it's so fundamentally important for the entire tool. I don't understand how this issue didn't "hit the fan" a long time ago. Maybe I'm missing something...

**Comment by tcfurrer** [comment]
I'm not sure that calls to getBoundsInLocal() are the only unsafe thing that TestFX is doing. Basically, accessing almost anything in the scene graph directly from the test thread is subject to the same sort of risk.

**Comment by adamish** [comment]
> We believe we've successfully worked around this bug by **_overriding almost every method in FxRobot to call super inside a waitForAsyncFx()_**. It's a bit painful to override so many methods, but since each one only needs a single line of code in the body, this code could be automatically generated.

I have followed a pretty much similar approach on a very large code base, 1000s of tests, and definitely fixed stability issues

Another approach I've taken many years ago before discovering testFX was to have a custom JUnit rule which ran all the test methods on the FX thread. I think something similar should be possible with JUnit 5 extensions.

**Comment by tcfurrer** [comment]
@adamish Thanks for sharing that reply.

The trick of running test methods on the FX thread is cool, but it definitely imposes some other limitations which prevent me from using it.  Namely, it puts all test code into the FX event loop, which has huge implications.

I'm considering this case: A test presses a Button and then needs to check for the expected result. That Button's onAction() is using a runLater() to do it's work. So the test cannot simply immediately check for the result. The test must itself use a runLater() in order to see the result. This means that all GUI tests would have to be implemented as a list of Runnables which each do a single piece of robotic interaction or checking (not both together). I suppose that could work, but it's certainly a strange coding style.

In case anyone thinks "well then just don't allow production event handlers to make use of runLater()"... this is actually good practice in general because the user expects visible things to happen immediately after they activate a control. For example, the button styling should change immediately. Menus should hide immediately. If the action itself might take a while, then these things won't happen unless a runLater() is used. Not to mention the fact that it's a royal pain to use the debugger when Menus and other popups are stuck on top of your IDE because you needed to debug the action code.
 
Another problem is that things in TestFX like waitForFxEvents() become useless when running the test on the FX thread. This means that if you don't know how many layers of runLater() the production code does, it's kind of impossible to reliably match that in the test. Should we just do a chain of 10 runLater() between each little Runnable of the test to address this issue? You see, it's getting pretty ridiculous now...

Maybe there is some clever way to make use of nested event looping to overcome this? That breaks my brain, and asks far too much of the casual TestFX test writer getting bitten by this complex multi-threading issue...

If I'm missing something here... I'd love to hear from anyone who can see it.
